/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AutenticacaoRespostaDto,
  ErroRespostaDto,
  LimiteRequisicoesRespostaDto,
  LoginDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type autenticacaoControllerLoginResponse200 = {
  data: AutenticacaoRespostaDto
  status: 200
}

export type autenticacaoControllerLoginResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type autenticacaoControllerLoginResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type autenticacaoControllerLoginResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type autenticacaoControllerLoginResponse415 = {
  data: ErroRespostaDto
  status: 415
}

export type autenticacaoControllerLoginResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type autenticacaoControllerLoginResponseSuccess = (autenticacaoControllerLoginResponse200) & {
  headers: Headers;
};
export type autenticacaoControllerLoginResponseError = (autenticacaoControllerLoginResponse400 | autenticacaoControllerLoginResponse401 | autenticacaoControllerLoginResponse403 | autenticacaoControllerLoginResponse415 | autenticacaoControllerLoginResponse429) & {
  headers: Headers;
};

export type autenticacaoControllerLoginResponse = (autenticacaoControllerLoginResponseSuccess | autenticacaoControllerLoginResponseError)

export const getAutenticacaoControllerLoginUrl = () => {




  return `${apiBaseUrl}/auth/login`
}

export const autenticacaoControllerLogin = async (loginDto: LoginDto, options?: Parameters<typeof httpClient>[1]): Promise<autenticacaoControllerLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<autenticacaoControllerLoginResponse>(getAutenticacaoControllerLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginDto)
  }
);}





export const getAutenticacaoControllerLoginMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof autenticacaoControllerLogin>>, TError,AutenticacaoControllerLoginMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof autenticacaoControllerLogin>>, TError,AutenticacaoControllerLoginMutationVariables, TContext> => {

const mutationKey = ['autenticacaoControllerLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof autenticacaoControllerLogin>>, AutenticacaoControllerLoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  autenticacaoControllerLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AutenticacaoControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof autenticacaoControllerLogin>>>
    export type AutenticacaoControllerLoginMutationBody = LoginDto
    export type AutenticacaoControllerLoginMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type AutenticacaoControllerLoginMutationVariables = {data: LoginDto}

    export const useAutenticacaoControllerLogin = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof autenticacaoControllerLogin>>, TError,AutenticacaoControllerLoginMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof autenticacaoControllerLogin>>,
        TError,
        AutenticacaoControllerLoginMutationVariables,
        TContext
      > => {
      return useMutation(getAutenticacaoControllerLoginMutationOptions(options), queryClient);
    }
    export type autenticacaoControllerMeResponse200 = {
  data: AutenticacaoRespostaDto
  status: 200
}

export type autenticacaoControllerMeResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type autenticacaoControllerMeResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type autenticacaoControllerMeResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type autenticacaoControllerMeResponseSuccess = (autenticacaoControllerMeResponse200) & {
  headers: Headers;
};
export type autenticacaoControllerMeResponseError = (autenticacaoControllerMeResponse401 | autenticacaoControllerMeResponse403 | autenticacaoControllerMeResponse429) & {
  headers: Headers;
};

export type autenticacaoControllerMeResponse = (autenticacaoControllerMeResponseSuccess | autenticacaoControllerMeResponseError)

export const getAutenticacaoControllerMeUrl = () => {




  return `${apiBaseUrl}/auth/me`
}

export const autenticacaoControllerMe = async ( options?: Parameters<typeof httpClient>[1]): Promise<autenticacaoControllerMeResponse> => {

  return httpClient<autenticacaoControllerMeResponse>(getAutenticacaoControllerMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAutenticacaoControllerMeQueryKey = () => {
    return [
    `${apiBaseUrl}/auth/me`
    ] as const;
    }


export const getAutenticacaoControllerMeQueryOptions = <TData = Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAutenticacaoControllerMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof autenticacaoControllerMe>>> = ({ signal }) => autenticacaoControllerMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AutenticacaoControllerMeQueryResult = NonNullable<Awaited<ReturnType<typeof autenticacaoControllerMe>>>
export type AutenticacaoControllerMeQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useAutenticacaoControllerMe<TData = Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof autenticacaoControllerMe>>,
          TError,
          Awaited<ReturnType<typeof autenticacaoControllerMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAutenticacaoControllerMe<TData = Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof autenticacaoControllerMe>>,
          TError,
          Awaited<ReturnType<typeof autenticacaoControllerMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAutenticacaoControllerMe<TData = Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAutenticacaoControllerMe<TData = Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerMe>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAutenticacaoControllerMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type autenticacaoControllerCsrfTokenResponse200 = {
  data: void
  status: 200
}

export type autenticacaoControllerCsrfTokenResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type autenticacaoControllerCsrfTokenResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type autenticacaoControllerCsrfTokenResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type autenticacaoControllerCsrfTokenResponseSuccess = (autenticacaoControllerCsrfTokenResponse200) & {
  headers: Headers;
};
export type autenticacaoControllerCsrfTokenResponseError = (autenticacaoControllerCsrfTokenResponse401 | autenticacaoControllerCsrfTokenResponse403 | autenticacaoControllerCsrfTokenResponse429) & {
  headers: Headers;
};

export type autenticacaoControllerCsrfTokenResponse = (autenticacaoControllerCsrfTokenResponseSuccess | autenticacaoControllerCsrfTokenResponseError)

export const getAutenticacaoControllerCsrfTokenUrl = () => {




  return `${apiBaseUrl}/auth/csrf`
}

/**
 * @summary Renova o token CSRF da sessão atual
 */
export const autenticacaoControllerCsrfToken = async ( options?: Parameters<typeof httpClient>[1]): Promise<autenticacaoControllerCsrfTokenResponse> => {

  return httpClient<autenticacaoControllerCsrfTokenResponse>(getAutenticacaoControllerCsrfTokenUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAutenticacaoControllerCsrfTokenQueryKey = () => {
    return [
    `${apiBaseUrl}/auth/csrf`
    ] as const;
    }


export const getAutenticacaoControllerCsrfTokenQueryOptions = <TData = Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAutenticacaoControllerCsrfTokenQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>> = ({ signal }) => autenticacaoControllerCsrfToken({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AutenticacaoControllerCsrfTokenQueryResult = NonNullable<Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>>
export type AutenticacaoControllerCsrfTokenQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useAutenticacaoControllerCsrfToken<TData = Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>,
          TError,
          Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAutenticacaoControllerCsrfToken<TData = Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>,
          TError,
          Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAutenticacaoControllerCsrfToken<TData = Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Renova o token CSRF da sessão atual
 */

export function useAutenticacaoControllerCsrfToken<TData = Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof autenticacaoControllerCsrfToken>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAutenticacaoControllerCsrfTokenQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type autenticacaoControllerLogoutResponse200 = {
  data: void
  status: 200
}

export type autenticacaoControllerLogoutResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type autenticacaoControllerLogoutResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type autenticacaoControllerLogoutResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type autenticacaoControllerLogoutResponseSuccess = (autenticacaoControllerLogoutResponse200) & {
  headers: Headers;
};
export type autenticacaoControllerLogoutResponseError = (autenticacaoControllerLogoutResponse401 | autenticacaoControllerLogoutResponse403 | autenticacaoControllerLogoutResponse429) & {
  headers: Headers;
};

export type autenticacaoControllerLogoutResponse = (autenticacaoControllerLogoutResponseSuccess | autenticacaoControllerLogoutResponseError)

export const getAutenticacaoControllerLogoutUrl = () => {




  return `${apiBaseUrl}/auth/logout`
}

export const autenticacaoControllerLogout = async ( options?: Parameters<typeof httpClient>[1]): Promise<autenticacaoControllerLogoutResponse> => {

  return httpClient<autenticacaoControllerLogoutResponse>(getAutenticacaoControllerLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getAutenticacaoControllerLogoutMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof autenticacaoControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof autenticacaoControllerLogout>>, TError,void, TContext> => {

const mutationKey = ['autenticacaoControllerLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof autenticacaoControllerLogout>>, void> = () => {


          return  autenticacaoControllerLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AutenticacaoControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof autenticacaoControllerLogout>>>

    export type AutenticacaoControllerLogoutMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto


    export const useAutenticacaoControllerLogout = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof autenticacaoControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof autenticacaoControllerLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAutenticacaoControllerLogoutMutationOptions(options), queryClient);
    }
