/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  ErroRespostaDto,
  LimiteRequisicoesRespostaDto,
  ServicosDashboardControllerObterParams,
  ServicosDashboardRespostaDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type servicosDashboardControllerObterResponse200 = {
  data: ServicosDashboardRespostaDto
  status: 200
}

export type servicosDashboardControllerObterResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type servicosDashboardControllerObterResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type servicosDashboardControllerObterResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type servicosDashboardControllerObterResponseSuccess = (servicosDashboardControllerObterResponse200) & {
  headers: Headers;
};
export type servicosDashboardControllerObterResponseError = (servicosDashboardControllerObterResponse401 | servicosDashboardControllerObterResponse403 | servicosDashboardControllerObterResponse429) & {
  headers: Headers;
};

export type servicosDashboardControllerObterResponse = (servicosDashboardControllerObterResponseSuccess | servicosDashboardControllerObterResponseError)

export const getServicosDashboardControllerObterUrl = (params?: ServicosDashboardControllerObterParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/dashboard/administrador/servicos?${stringifiedParams}` : `${apiBaseUrl}/dashboard/administrador/servicos`
}

/**
 * @summary Obtém indicadores e desempenho dos serviços
 */
export const servicosDashboardControllerObter = async (params?: ServicosDashboardControllerObterParams, options?: Parameters<typeof httpClient>[1]): Promise<servicosDashboardControllerObterResponse> => {

  return httpClient<servicosDashboardControllerObterResponse>(getServicosDashboardControllerObterUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getServicosDashboardControllerObterQueryKey = (params?: ServicosDashboardControllerObterParams,) => {
    return [
    `${apiBaseUrl}/dashboard/administrador/servicos`, ...(params ? [params] : [])
    ] as const;
    }


export const getServicosDashboardControllerObterQueryOptions = <TData = Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(params?: ServicosDashboardControllerObterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServicosDashboardControllerObterQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof servicosDashboardControllerObter>>> = ({ signal }) => servicosDashboardControllerObter(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServicosDashboardControllerObterQueryResult = NonNullable<Awaited<ReturnType<typeof servicosDashboardControllerObter>>>
export type ServicosDashboardControllerObterQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useServicosDashboardControllerObter<TData = Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: undefined |  ServicosDashboardControllerObterParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof servicosDashboardControllerObter>>,
          TError,
          Awaited<ReturnType<typeof servicosDashboardControllerObter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServicosDashboardControllerObter<TData = Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: ServicosDashboardControllerObterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof servicosDashboardControllerObter>>,
          TError,
          Awaited<ReturnType<typeof servicosDashboardControllerObter>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServicosDashboardControllerObter<TData = Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: ServicosDashboardControllerObterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Obtém indicadores e desempenho dos serviços
 */

export function useServicosDashboardControllerObter<TData = Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: ServicosDashboardControllerObterParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicosDashboardControllerObter>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServicosDashboardControllerObterQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






