/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AtualizarServicoDto,
  CriarServicoDto,
  ErroRespostaDto,
  ListaServicosRespostaDto,
  ServicoControllerListarParams,
  ServicoRespostaDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type servicoControllerCriarResponse201 = {
  data: ServicoRespostaDto
  status: 201
}

export type servicoControllerCriarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type servicoControllerCriarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type servicoControllerCriarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type servicoControllerCriarResponseSuccess = (servicoControllerCriarResponse201) & {
  headers: Headers;
};
export type servicoControllerCriarResponseError = (servicoControllerCriarResponse400 | servicoControllerCriarResponse404 | servicoControllerCriarResponse409) & {
  headers: Headers;
};

export type servicoControllerCriarResponse = (servicoControllerCriarResponseSuccess | servicoControllerCriarResponseError)

export const getServicoControllerCriarUrl = () => {




  return `${apiBaseUrl}/servicos`
}

/**
 * @summary Cria um serviço
 */
export const servicoControllerCriar = async (criarServicoDto: CriarServicoDto, options?: Parameters<typeof httpClient>[1]): Promise<servicoControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<servicoControllerCriarResponse>(getServicoControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarServicoDto)
  }
);}





export const getServicoControllerCriarMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof servicoControllerCriar>>, TError,ServicoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof servicoControllerCriar>>, TError,ServicoControllerCriarMutationVariables, TContext> => {

const mutationKey = ['servicoControllerCriar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof servicoControllerCriar>>, ServicoControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  servicoControllerCriar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ServicoControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof servicoControllerCriar>>>
    export type ServicoControllerCriarMutationBody = CriarServicoDto
    export type ServicoControllerCriarMutationError = ErroRespostaDto
    export type ServicoControllerCriarMutationVariables = {data: CriarServicoDto}

    /**
 * @summary Cria um serviço
 */
export const useServicoControllerCriar = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof servicoControllerCriar>>, TError,ServicoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof servicoControllerCriar>>,
        TError,
        ServicoControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getServicoControllerCriarMutationOptions(options), queryClient);
    }
    export type servicoControllerListarResponse200 = {
  data: ListaServicosRespostaDto
  status: 200
}

export type servicoControllerListarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type servicoControllerListarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type servicoControllerListarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type servicoControllerListarResponseSuccess = (servicoControllerListarResponse200) & {
  headers: Headers;
};
export type servicoControllerListarResponseError = (servicoControllerListarResponse400 | servicoControllerListarResponse404 | servicoControllerListarResponse409) & {
  headers: Headers;
};

export type servicoControllerListarResponse = (servicoControllerListarResponseSuccess | servicoControllerListarResponseError)

export const getServicoControllerListarUrl = (params?: ServicoControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/servicos?${stringifiedParams}` : `${apiBaseUrl}/servicos`
}

/**
 * @summary Lista os serviços de forma paginada
 */
export const servicoControllerListar = async (params?: ServicoControllerListarParams, options?: Parameters<typeof httpClient>[1]): Promise<servicoControllerListarResponse> => {

  return httpClient<servicoControllerListarResponse>(getServicoControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getServicoControllerListarQueryKey = (params?: ServicoControllerListarParams,) => {
    return [
    `${apiBaseUrl}/servicos`, ...(params ? [params] : [])
    ] as const;
    }


export const getServicoControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof servicoControllerListar>>, TError = ErroRespostaDto>(params?: ServicoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServicoControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof servicoControllerListar>>> = ({ signal }) => servicoControllerListar(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof servicoControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServicoControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof servicoControllerListar>>>
export type ServicoControllerListarQueryError = ErroRespostaDto


export function useServicoControllerListar<TData = Awaited<ReturnType<typeof servicoControllerListar>>, TError = ErroRespostaDto>(
 params: undefined |  ServicoControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof servicoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof servicoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServicoControllerListar<TData = Awaited<ReturnType<typeof servicoControllerListar>>, TError = ErroRespostaDto>(
 params?: ServicoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof servicoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof servicoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServicoControllerListar<TData = Awaited<ReturnType<typeof servicoControllerListar>>, TError = ErroRespostaDto>(
 params?: ServicoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista os serviços de forma paginada
 */

export function useServicoControllerListar<TData = Awaited<ReturnType<typeof servicoControllerListar>>, TError = ErroRespostaDto>(
 params?: ServicoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServicoControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type servicoControllerBuscarResponse200 = {
  data: ServicoRespostaDto
  status: 200
}

export type servicoControllerBuscarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type servicoControllerBuscarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type servicoControllerBuscarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type servicoControllerBuscarResponseSuccess = (servicoControllerBuscarResponse200) & {
  headers: Headers;
};
export type servicoControllerBuscarResponseError = (servicoControllerBuscarResponse400 | servicoControllerBuscarResponse404 | servicoControllerBuscarResponse409) & {
  headers: Headers;
};

export type servicoControllerBuscarResponse = (servicoControllerBuscarResponseSuccess | servicoControllerBuscarResponseError)

export const getServicoControllerBuscarUrl = (id: number,) => {




  return `${apiBaseUrl}/servicos/${id}`
}

/**
 * @summary Busca um serviço pelo identificador
 */
export const servicoControllerBuscar = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<servicoControllerBuscarResponse> => {

  return httpClient<servicoControllerBuscarResponse>(getServicoControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getServicoControllerBuscarQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/servicos/${id}`
    ] as const;
    }


export const getServicoControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof servicoControllerBuscar>>, TError = ErroRespostaDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServicoControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof servicoControllerBuscar>>> = ({ signal }) => servicoControllerBuscar(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof servicoControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServicoControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof servicoControllerBuscar>>>
export type ServicoControllerBuscarQueryError = ErroRespostaDto


export function useServicoControllerBuscar<TData = Awaited<ReturnType<typeof servicoControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof servicoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof servicoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServicoControllerBuscar<TData = Awaited<ReturnType<typeof servicoControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof servicoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof servicoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServicoControllerBuscar<TData = Awaited<ReturnType<typeof servicoControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Busca um serviço pelo identificador
 */

export function useServicoControllerBuscar<TData = Awaited<ReturnType<typeof servicoControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servicoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServicoControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type servicoControllerAtualizarResponse200 = {
  data: ServicoRespostaDto
  status: 200
}

export type servicoControllerAtualizarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type servicoControllerAtualizarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type servicoControllerAtualizarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type servicoControllerAtualizarResponseSuccess = (servicoControllerAtualizarResponse200) & {
  headers: Headers;
};
export type servicoControllerAtualizarResponseError = (servicoControllerAtualizarResponse400 | servicoControllerAtualizarResponse404 | servicoControllerAtualizarResponse409) & {
  headers: Headers;
};

export type servicoControllerAtualizarResponse = (servicoControllerAtualizarResponseSuccess | servicoControllerAtualizarResponseError)

export const getServicoControllerAtualizarUrl = (id: number,) => {




  return `${apiBaseUrl}/servicos/${id}`
}

/**
 * @summary Atualiza um serviço pelo identificador
 */
export const servicoControllerAtualizar = async (id: number,
    atualizarServicoDto: AtualizarServicoDto, options?: Parameters<typeof httpClient>[1]): Promise<servicoControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<servicoControllerAtualizarResponse>(getServicoControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarServicoDto)
  }
);}





export const getServicoControllerAtualizarMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof servicoControllerAtualizar>>, TError,ServicoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof servicoControllerAtualizar>>, TError,ServicoControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['servicoControllerAtualizar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof servicoControllerAtualizar>>, ServicoControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  servicoControllerAtualizar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ServicoControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof servicoControllerAtualizar>>>
    export type ServicoControllerAtualizarMutationBody = AtualizarServicoDto
    export type ServicoControllerAtualizarMutationError = ErroRespostaDto
    export type ServicoControllerAtualizarMutationVariables = {id: number;data: AtualizarServicoDto}

    /**
 * @summary Atualiza um serviço pelo identificador
 */
export const useServicoControllerAtualizar = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof servicoControllerAtualizar>>, TError,ServicoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof servicoControllerAtualizar>>,
        TError,
        ServicoControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getServicoControllerAtualizarMutationOptions(options), queryClient);
    }
    export type servicoControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type servicoControllerRemoverResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type servicoControllerRemoverResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type servicoControllerRemoverResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type servicoControllerRemoverResponseSuccess = (servicoControllerRemoverResponse200) & {
  headers: Headers;
};
export type servicoControllerRemoverResponseError = (servicoControllerRemoverResponse400 | servicoControllerRemoverResponse404 | servicoControllerRemoverResponse409) & {
  headers: Headers;
};

export type servicoControllerRemoverResponse = (servicoControllerRemoverResponseSuccess | servicoControllerRemoverResponseError)

export const getServicoControllerRemoverUrl = (id: number,) => {




  return `${apiBaseUrl}/servicos/${id}`
}

/**
 * @summary Remove um serviço pelo identificador
 */
export const servicoControllerRemover = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<servicoControllerRemoverResponse> => {

  return httpClient<servicoControllerRemoverResponse>(getServicoControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getServicoControllerRemoverMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof servicoControllerRemover>>, TError,ServicoControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof servicoControllerRemover>>, TError,ServicoControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['servicoControllerRemover'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof servicoControllerRemover>>, ServicoControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  servicoControllerRemover(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ServicoControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof servicoControllerRemover>>>

    export type ServicoControllerRemoverMutationError = ErroRespostaDto
    export type ServicoControllerRemoverMutationVariables = {id: number}

    /**
 * @summary Remove um serviço pelo identificador
 */
export const useServicoControllerRemover = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof servicoControllerRemover>>, TError,ServicoControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof servicoControllerRemover>>,
        TError,
        ServicoControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getServicoControllerRemoverMutationOptions(options), queryClient);
    }
