/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AtualizarEnderecoDto,
  CriarEnderecoDto,
  EnderecoControllerBuscar200,
  EnderecoControllerListarParams
} from '../models';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type enderecoControllerCriarResponse201 = {
  data: void
  status: 201
}

export type enderecoControllerCriarResponseSuccess = (enderecoControllerCriarResponse201) & {
  headers: Headers;
};
;

export type enderecoControllerCriarResponse = (enderecoControllerCriarResponseSuccess)

export const getEnderecoControllerCriarUrl = () => {




  return `/enderecos`
}

export const enderecoControllerCriar = async (criarEnderecoDto: CriarEnderecoDto, options?: RequestInit): Promise<enderecoControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getEnderecoControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarEnderecoDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: enderecoControllerCriarResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as enderecoControllerCriarResponse
}





export const getEnderecoControllerCriarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enderecoControllerCriar>>, TError,EnderecoControllerCriarMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof enderecoControllerCriar>>, TError,EnderecoControllerCriarMutationVariables, TContext> => {

const mutationKey = ['enderecoControllerCriar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enderecoControllerCriar>>, EnderecoControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  enderecoControllerCriar(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EnderecoControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof enderecoControllerCriar>>>
    export type EnderecoControllerCriarMutationBody = CriarEnderecoDto
    export type EnderecoControllerCriarMutationError = unknown
    export type EnderecoControllerCriarMutationVariables = {data: CriarEnderecoDto}

    export const useEnderecoControllerCriar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enderecoControllerCriar>>, TError,EnderecoControllerCriarMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof enderecoControllerCriar>>,
        TError,
        EnderecoControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getEnderecoControllerCriarMutationOptions(options), queryClient);
    }
    export type enderecoControllerListarResponse200 = {
  data: void
  status: 200
}

export type enderecoControllerListarResponseSuccess = (enderecoControllerListarResponse200) & {
  headers: Headers;
};
;

export type enderecoControllerListarResponse = (enderecoControllerListarResponseSuccess)

export const getEnderecoControllerListarUrl = (params: EnderecoControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/enderecos?${stringifiedParams}` : `/enderecos`
}

export const enderecoControllerListar = async (params: EnderecoControllerListarParams, options?: RequestInit): Promise<enderecoControllerListarResponse> => {

  const res = await fetch(getEnderecoControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: enderecoControllerListarResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as enderecoControllerListarResponse
}





export const getEnderecoControllerListarQueryKey = (params?: EnderecoControllerListarParams,) => {
    return [
    `/enderecos`, ...(params ? [params] : [])
    ] as const;
    }


export const getEnderecoControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof enderecoControllerListar>>, TError = unknown>(params: EnderecoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerListar>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEnderecoControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof enderecoControllerListar>>> = ({ signal }) => enderecoControllerListar(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EnderecoControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof enderecoControllerListar>>>
export type EnderecoControllerListarQueryError = unknown


export function useEnderecoControllerListar<TData = Awaited<ReturnType<typeof enderecoControllerListar>>, TError = unknown>(
 params: EnderecoControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof enderecoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof enderecoControllerListar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnderecoControllerListar<TData = Awaited<ReturnType<typeof enderecoControllerListar>>, TError = unknown>(
 params: EnderecoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof enderecoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof enderecoControllerListar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnderecoControllerListar<TData = Awaited<ReturnType<typeof enderecoControllerListar>>, TError = unknown>(
 params: EnderecoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerListar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useEnderecoControllerListar<TData = Awaited<ReturnType<typeof enderecoControllerListar>>, TError = unknown>(
 params: EnderecoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerListar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEnderecoControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type enderecoControllerBuscarResponse200 = {
  data: EnderecoControllerBuscar200
  status: 200
}

export type enderecoControllerBuscarResponseSuccess = (enderecoControllerBuscarResponse200) & {
  headers: Headers;
};
;

export type enderecoControllerBuscarResponse = (enderecoControllerBuscarResponseSuccess)

export const getEnderecoControllerBuscarUrl = (id: number,) => {




  return `/enderecos/${id}`
}

export const enderecoControllerBuscar = async (id: number, options?: RequestInit): Promise<enderecoControllerBuscarResponse> => {

  const res = await fetch(getEnderecoControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: enderecoControllerBuscarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as enderecoControllerBuscarResponse
}





export const getEnderecoControllerBuscarQueryKey = (id: number,) => {
    return [
    `/enderecos/${id}`
    ] as const;
    }


export const getEnderecoControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEnderecoControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof enderecoControllerBuscar>>> = ({ signal }) => enderecoControllerBuscar(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EnderecoControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof enderecoControllerBuscar>>>
export type EnderecoControllerBuscarQueryError = unknown


export function useEnderecoControllerBuscar<TData = Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof enderecoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof enderecoControllerBuscar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnderecoControllerBuscar<TData = Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof enderecoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof enderecoControllerBuscar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEnderecoControllerBuscar<TData = Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useEnderecoControllerBuscar<TData = Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof enderecoControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEnderecoControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type enderecoControllerAtualizarResponse200 = {
  data: void
  status: 200
}

export type enderecoControllerAtualizarResponseSuccess = (enderecoControllerAtualizarResponse200) & {
  headers: Headers;
};
;

export type enderecoControllerAtualizarResponse = (enderecoControllerAtualizarResponseSuccess)

export const getEnderecoControllerAtualizarUrl = (id: number,) => {




  return `/enderecos/${id}`
}

export const enderecoControllerAtualizar = async (id: number,
    atualizarEnderecoDto: AtualizarEnderecoDto, options?: RequestInit): Promise<enderecoControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getEnderecoControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarEnderecoDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: enderecoControllerAtualizarResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as enderecoControllerAtualizarResponse
}





export const getEnderecoControllerAtualizarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enderecoControllerAtualizar>>, TError,EnderecoControllerAtualizarMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof enderecoControllerAtualizar>>, TError,EnderecoControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['enderecoControllerAtualizar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enderecoControllerAtualizar>>, EnderecoControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  enderecoControllerAtualizar(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EnderecoControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof enderecoControllerAtualizar>>>
    export type EnderecoControllerAtualizarMutationBody = AtualizarEnderecoDto
    export type EnderecoControllerAtualizarMutationError = unknown
    export type EnderecoControllerAtualizarMutationVariables = {id: number;data: AtualizarEnderecoDto}

    export const useEnderecoControllerAtualizar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enderecoControllerAtualizar>>, TError,EnderecoControllerAtualizarMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof enderecoControllerAtualizar>>,
        TError,
        EnderecoControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getEnderecoControllerAtualizarMutationOptions(options), queryClient);
    }
    export type enderecoControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type enderecoControllerRemoverResponseSuccess = (enderecoControllerRemoverResponse200) & {
  headers: Headers;
};
;

export type enderecoControllerRemoverResponse = (enderecoControllerRemoverResponseSuccess)

export const getEnderecoControllerRemoverUrl = (id: number,) => {




  return `/enderecos/${id}`
}

export const enderecoControllerRemover = async (id: number, options?: RequestInit): Promise<enderecoControllerRemoverResponse> => {

  const res = await fetch(getEnderecoControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: enderecoControllerRemoverResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as enderecoControllerRemoverResponse
}





export const getEnderecoControllerRemoverMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enderecoControllerRemover>>, TError,EnderecoControllerRemoverMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof enderecoControllerRemover>>, TError,EnderecoControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['enderecoControllerRemover'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enderecoControllerRemover>>, EnderecoControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  enderecoControllerRemover(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EnderecoControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof enderecoControllerRemover>>>

    export type EnderecoControllerRemoverMutationError = unknown
    export type EnderecoControllerRemoverMutationVariables = {id: number}

    export const useEnderecoControllerRemover = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enderecoControllerRemover>>, TError,EnderecoControllerRemoverMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof enderecoControllerRemover>>,
        TError,
        EnderecoControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getEnderecoControllerRemoverMutationOptions(options), queryClient);
    }
