/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AtualizarUsuarioDto,
  CriarUsuarioDto,
  ErroRespostaDto,
  ListaUsuariosRespostaDto,
  UsuarioControllerListarParams,
  UsuarioRespostaDto
} from '../models';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type usuarioControllerCriarResponse201 = {
  data: UsuarioRespostaDto
  status: 201
}

export type usuarioControllerCriarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type usuarioControllerCriarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type usuarioControllerCriarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type usuarioControllerCriarResponseSuccess = (usuarioControllerCriarResponse201) & {
  headers: Headers;
};
export type usuarioControllerCriarResponseError = (usuarioControllerCriarResponse400 | usuarioControllerCriarResponse404 | usuarioControllerCriarResponse409) & {
  headers: Headers;
};

export type usuarioControllerCriarResponse = (usuarioControllerCriarResponseSuccess | usuarioControllerCriarResponseError)

export const getUsuarioControllerCriarUrl = () => {




  return `/usuarios`
}

/**
 * @summary Cria um usuário administrador
 */
export const usuarioControllerCriar = async (criarUsuarioDto: CriarUsuarioDto, options?: RequestInit): Promise<usuarioControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getUsuarioControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarUsuarioDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usuarioControllerCriarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioControllerCriarResponse
}





export const getUsuarioControllerCriarMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usuarioControllerCriar>>, TError,UsuarioControllerCriarMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof usuarioControllerCriar>>, TError,UsuarioControllerCriarMutationVariables, TContext> => {

const mutationKey = ['usuarioControllerCriar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usuarioControllerCriar>>, UsuarioControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  usuarioControllerCriar(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsuarioControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof usuarioControllerCriar>>>
    export type UsuarioControllerCriarMutationBody = CriarUsuarioDto
    export type UsuarioControllerCriarMutationError = ErroRespostaDto
    export type UsuarioControllerCriarMutationVariables = {data: CriarUsuarioDto}

    /**
 * @summary Cria um usuário administrador
 */
export const useUsuarioControllerCriar = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usuarioControllerCriar>>, TError,UsuarioControllerCriarMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usuarioControllerCriar>>,
        TError,
        UsuarioControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getUsuarioControllerCriarMutationOptions(options), queryClient);
    }
    export type usuarioControllerListarResponse200 = {
  data: ListaUsuariosRespostaDto
  status: 200
}

export type usuarioControllerListarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type usuarioControllerListarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type usuarioControllerListarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type usuarioControllerListarResponseSuccess = (usuarioControllerListarResponse200) & {
  headers: Headers;
};
export type usuarioControllerListarResponseError = (usuarioControllerListarResponse400 | usuarioControllerListarResponse404 | usuarioControllerListarResponse409) & {
  headers: Headers;
};

export type usuarioControllerListarResponse = (usuarioControllerListarResponseSuccess | usuarioControllerListarResponseError)

export const getUsuarioControllerListarUrl = (params: UsuarioControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/usuarios?${stringifiedParams}` : `/usuarios`
}

/**
 * @summary Lista usuários administradores
 */
export const usuarioControllerListar = async (params: UsuarioControllerListarParams, options?: RequestInit): Promise<usuarioControllerListarResponse> => {

  const res = await fetch(getUsuarioControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usuarioControllerListarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioControllerListarResponse
}





export const getUsuarioControllerListarQueryKey = (params?: UsuarioControllerListarParams,) => {
    return [
    `/usuarios`, ...(params ? [params] : [])
    ] as const;
    }


export const getUsuarioControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof usuarioControllerListar>>, TError = ErroRespostaDto>(params: UsuarioControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerListar>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsuarioControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usuarioControllerListar>>> = ({ signal }) => usuarioControllerListar(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsuarioControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof usuarioControllerListar>>>
export type UsuarioControllerListarQueryError = ErroRespostaDto


export function useUsuarioControllerListar<TData = Awaited<ReturnType<typeof usuarioControllerListar>>, TError = ErroRespostaDto>(
 params: UsuarioControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usuarioControllerListar>>,
          TError,
          Awaited<ReturnType<typeof usuarioControllerListar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsuarioControllerListar<TData = Awaited<ReturnType<typeof usuarioControllerListar>>, TError = ErroRespostaDto>(
 params: UsuarioControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usuarioControllerListar>>,
          TError,
          Awaited<ReturnType<typeof usuarioControllerListar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsuarioControllerListar<TData = Awaited<ReturnType<typeof usuarioControllerListar>>, TError = ErroRespostaDto>(
 params: UsuarioControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerListar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista usuários administradores
 */

export function useUsuarioControllerListar<TData = Awaited<ReturnType<typeof usuarioControllerListar>>, TError = ErroRespostaDto>(
 params: UsuarioControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerListar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsuarioControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type usuarioControllerBuscarResponse200 = {
  data: UsuarioRespostaDto
  status: 200
}

export type usuarioControllerBuscarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type usuarioControllerBuscarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type usuarioControllerBuscarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type usuarioControllerBuscarResponseSuccess = (usuarioControllerBuscarResponse200) & {
  headers: Headers;
};
export type usuarioControllerBuscarResponseError = (usuarioControllerBuscarResponse400 | usuarioControllerBuscarResponse404 | usuarioControllerBuscarResponse409) & {
  headers: Headers;
};

export type usuarioControllerBuscarResponse = (usuarioControllerBuscarResponseSuccess | usuarioControllerBuscarResponseError)

export const getUsuarioControllerBuscarUrl = (id: number,) => {




  return `/usuarios/${id}`
}

/**
 * @summary Busca um usuário administrador
 */
export const usuarioControllerBuscar = async (id: number, options?: RequestInit): Promise<usuarioControllerBuscarResponse> => {

  const res = await fetch(getUsuarioControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usuarioControllerBuscarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioControllerBuscarResponse
}





export const getUsuarioControllerBuscarQueryKey = (id: number,) => {
    return [
    `/usuarios/${id}`
    ] as const;
    }


export const getUsuarioControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError = ErroRespostaDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsuarioControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usuarioControllerBuscar>>> = ({ signal }) => usuarioControllerBuscar(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsuarioControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof usuarioControllerBuscar>>>
export type UsuarioControllerBuscarQueryError = ErroRespostaDto


export function useUsuarioControllerBuscar<TData = Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usuarioControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof usuarioControllerBuscar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsuarioControllerBuscar<TData = Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usuarioControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof usuarioControllerBuscar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsuarioControllerBuscar<TData = Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Busca um usuário administrador
 */

export function useUsuarioControllerBuscar<TData = Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usuarioControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsuarioControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type usuarioControllerAtualizarResponse200 = {
  data: UsuarioRespostaDto
  status: 200
}

export type usuarioControllerAtualizarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type usuarioControllerAtualizarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type usuarioControllerAtualizarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type usuarioControllerAtualizarResponseSuccess = (usuarioControllerAtualizarResponse200) & {
  headers: Headers;
};
export type usuarioControllerAtualizarResponseError = (usuarioControllerAtualizarResponse400 | usuarioControllerAtualizarResponse404 | usuarioControllerAtualizarResponse409) & {
  headers: Headers;
};

export type usuarioControllerAtualizarResponse = (usuarioControllerAtualizarResponseSuccess | usuarioControllerAtualizarResponseError)

export const getUsuarioControllerAtualizarUrl = (id: number,) => {




  return `/usuarios/${id}`
}

/**
 * @summary Atualiza um usuário administrador
 */
export const usuarioControllerAtualizar = async (id: number,
    atualizarUsuarioDto: AtualizarUsuarioDto, options?: RequestInit): Promise<usuarioControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getUsuarioControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarUsuarioDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usuarioControllerAtualizarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioControllerAtualizarResponse
}





export const getUsuarioControllerAtualizarMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usuarioControllerAtualizar>>, TError,UsuarioControllerAtualizarMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof usuarioControllerAtualizar>>, TError,UsuarioControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['usuarioControllerAtualizar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usuarioControllerAtualizar>>, UsuarioControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  usuarioControllerAtualizar(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsuarioControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof usuarioControllerAtualizar>>>
    export type UsuarioControllerAtualizarMutationBody = AtualizarUsuarioDto
    export type UsuarioControllerAtualizarMutationError = ErroRespostaDto
    export type UsuarioControllerAtualizarMutationVariables = {id: number;data: AtualizarUsuarioDto}

    /**
 * @summary Atualiza um usuário administrador
 */
export const useUsuarioControllerAtualizar = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usuarioControllerAtualizar>>, TError,UsuarioControllerAtualizarMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usuarioControllerAtualizar>>,
        TError,
        UsuarioControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getUsuarioControllerAtualizarMutationOptions(options), queryClient);
    }
    export type usuarioControllerRemoverResponse204 = {
  data: void
  status: 204
}

export type usuarioControllerRemoverResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type usuarioControllerRemoverResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type usuarioControllerRemoverResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type usuarioControllerRemoverResponseSuccess = (usuarioControllerRemoverResponse204) & {
  headers: Headers;
};
export type usuarioControllerRemoverResponseError = (usuarioControllerRemoverResponse400 | usuarioControllerRemoverResponse404 | usuarioControllerRemoverResponse409) & {
  headers: Headers;
};

export type usuarioControllerRemoverResponse = (usuarioControllerRemoverResponseSuccess | usuarioControllerRemoverResponseError)

export const getUsuarioControllerRemoverUrl = (id: number,) => {




  return `/usuarios/${id}`
}

/**
 * @summary Remove um usuário administrador
 */
export const usuarioControllerRemover = async (id: number, options?: RequestInit): Promise<usuarioControllerRemoverResponse> => {

  const res = await fetch(getUsuarioControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: usuarioControllerRemoverResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as usuarioControllerRemoverResponse
}





export const getUsuarioControllerRemoverMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usuarioControllerRemover>>, TError,UsuarioControllerRemoverMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof usuarioControllerRemover>>, TError,UsuarioControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['usuarioControllerRemover'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usuarioControllerRemover>>, UsuarioControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  usuarioControllerRemover(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsuarioControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof usuarioControllerRemover>>>

    export type UsuarioControllerRemoverMutationError = ErroRespostaDto
    export type UsuarioControllerRemoverMutationVariables = {id: number}

    /**
 * @summary Remove um usuário administrador
 */
export const useUsuarioControllerRemover = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usuarioControllerRemover>>, TError,UsuarioControllerRemoverMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usuarioControllerRemover>>,
        TError,
        UsuarioControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getUsuarioControllerRemoverMutationOptions(options), queryClient);
    }
