/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AtualizarComissaoDto,
  ComissaoControllerAtualizar200,
  ComissaoControllerBuscar200,
  ComissaoControllerCriar201,
  ComissaoControllerListarParams,
  CriarComissaoDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type comissaoControllerCriarResponse201 = {
  data: ComissaoControllerCriar201
  status: 201
}

export type comissaoControllerCriarResponseSuccess = (comissaoControllerCriarResponse201) & {
  headers: Headers;
};
;

export type comissaoControllerCriarResponse = (comissaoControllerCriarResponseSuccess)

export const getComissaoControllerCriarUrl = () => {




  return `${apiBaseUrl}/comissoes`
}

export const comissaoControllerCriar = async (criarComissaoDto: CriarComissaoDto, options?: Parameters<typeof httpClient>[1]): Promise<comissaoControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<comissaoControllerCriarResponse>(getComissaoControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarComissaoDto)
  }
);}





export const getComissaoControllerCriarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof comissaoControllerCriar>>, TError,ComissaoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof comissaoControllerCriar>>, TError,ComissaoControllerCriarMutationVariables, TContext> => {

const mutationKey = ['comissaoControllerCriar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof comissaoControllerCriar>>, ComissaoControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  comissaoControllerCriar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ComissaoControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof comissaoControllerCriar>>>
    export type ComissaoControllerCriarMutationBody = CriarComissaoDto
    export type ComissaoControllerCriarMutationError = unknown
    export type ComissaoControllerCriarMutationVariables = {data: CriarComissaoDto}

    export const useComissaoControllerCriar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof comissaoControllerCriar>>, TError,ComissaoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof comissaoControllerCriar>>,
        TError,
        ComissaoControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getComissaoControllerCriarMutationOptions(options), queryClient);
    }
    export type comissaoControllerListarResponse200 = {
  data: void
  status: 200
}

export type comissaoControllerListarResponseSuccess = (comissaoControllerListarResponse200) & {
  headers: Headers;
};
;

export type comissaoControllerListarResponse = (comissaoControllerListarResponseSuccess)

export const getComissaoControllerListarUrl = (params?: ComissaoControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/comissoes?${stringifiedParams}` : `${apiBaseUrl}/comissoes`
}

export const comissaoControllerListar = async (params?: ComissaoControllerListarParams, options?: Parameters<typeof httpClient>[1]): Promise<comissaoControllerListarResponse> => {

  return httpClient<comissaoControllerListarResponse>(getComissaoControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getComissaoControllerListarQueryKey = (params?: ComissaoControllerListarParams,) => {
    return [
    `${apiBaseUrl}/comissoes`, ...(params ? [params] : [])
    ] as const;
    }


export const getComissaoControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof comissaoControllerListar>>, TError = unknown>(params?: ComissaoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getComissaoControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof comissaoControllerListar>>> = ({ signal }) => comissaoControllerListar(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ComissaoControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof comissaoControllerListar>>>
export type ComissaoControllerListarQueryError = unknown


export function useComissaoControllerListar<TData = Awaited<ReturnType<typeof comissaoControllerListar>>, TError = unknown>(
 params: undefined |  ComissaoControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof comissaoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof comissaoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useComissaoControllerListar<TData = Awaited<ReturnType<typeof comissaoControllerListar>>, TError = unknown>(
 params?: ComissaoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof comissaoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof comissaoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useComissaoControllerListar<TData = Awaited<ReturnType<typeof comissaoControllerListar>>, TError = unknown>(
 params?: ComissaoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useComissaoControllerListar<TData = Awaited<ReturnType<typeof comissaoControllerListar>>, TError = unknown>(
 params?: ComissaoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getComissaoControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type comissaoControllerBuscarResponse200 = {
  data: ComissaoControllerBuscar200
  status: 200
}

export type comissaoControllerBuscarResponseSuccess = (comissaoControllerBuscarResponse200) & {
  headers: Headers;
};
;

export type comissaoControllerBuscarResponse = (comissaoControllerBuscarResponseSuccess)

export const getComissaoControllerBuscarUrl = (id: number,) => {




  return `${apiBaseUrl}/comissoes/${id}`
}

export const comissaoControllerBuscar = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<comissaoControllerBuscarResponse> => {

  return httpClient<comissaoControllerBuscarResponse>(getComissaoControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getComissaoControllerBuscarQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/comissoes/${id}`
    ] as const;
    }


export const getComissaoControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getComissaoControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof comissaoControllerBuscar>>> = ({ signal }) => comissaoControllerBuscar(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ComissaoControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof comissaoControllerBuscar>>>
export type ComissaoControllerBuscarQueryError = unknown


export function useComissaoControllerBuscar<TData = Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof comissaoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof comissaoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useComissaoControllerBuscar<TData = Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof comissaoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof comissaoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useComissaoControllerBuscar<TData = Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useComissaoControllerBuscar<TData = Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof comissaoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getComissaoControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type comissaoControllerAtualizarResponse200 = {
  data: ComissaoControllerAtualizar200
  status: 200
}

export type comissaoControllerAtualizarResponseSuccess = (comissaoControllerAtualizarResponse200) & {
  headers: Headers;
};
;

export type comissaoControllerAtualizarResponse = (comissaoControllerAtualizarResponseSuccess)

export const getComissaoControllerAtualizarUrl = (id: number,) => {




  return `${apiBaseUrl}/comissoes/${id}`
}

export const comissaoControllerAtualizar = async (id: number,
    atualizarComissaoDto: AtualizarComissaoDto, options?: Parameters<typeof httpClient>[1]): Promise<comissaoControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<comissaoControllerAtualizarResponse>(getComissaoControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarComissaoDto)
  }
);}





export const getComissaoControllerAtualizarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof comissaoControllerAtualizar>>, TError,ComissaoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof comissaoControllerAtualizar>>, TError,ComissaoControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['comissaoControllerAtualizar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof comissaoControllerAtualizar>>, ComissaoControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  comissaoControllerAtualizar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ComissaoControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof comissaoControllerAtualizar>>>
    export type ComissaoControllerAtualizarMutationBody = AtualizarComissaoDto
    export type ComissaoControllerAtualizarMutationError = unknown
    export type ComissaoControllerAtualizarMutationVariables = {id: number;data: AtualizarComissaoDto}

    export const useComissaoControllerAtualizar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof comissaoControllerAtualizar>>, TError,ComissaoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof comissaoControllerAtualizar>>,
        TError,
        ComissaoControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getComissaoControllerAtualizarMutationOptions(options), queryClient);
    }
