/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AdministradorControllerListarParams,
  AtualizarAdministradorDto,
  CriarAdministradorDto,
  ErroRespostaDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type administradorControllerCriarResponse201 = {
  data: void
  status: 201
}

export type administradorControllerCriarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type administradorControllerCriarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type administradorControllerCriarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type administradorControllerCriarResponseSuccess = (administradorControllerCriarResponse201) & {
  headers: Headers;
};
export type administradorControllerCriarResponseError = (administradorControllerCriarResponse400 | administradorControllerCriarResponse404 | administradorControllerCriarResponse409) & {
  headers: Headers;
};

export type administradorControllerCriarResponse = (administradorControllerCriarResponseSuccess | administradorControllerCriarResponseError)

export const getAdministradorControllerCriarUrl = () => {




  return `${apiBaseUrl}/administradores`
}

/**
 * @summary Cria um administrador
 */
export const administradorControllerCriar = async (criarAdministradorDto: CriarAdministradorDto, options?: Parameters<typeof httpClient>[1]): Promise<administradorControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<administradorControllerCriarResponse>(getAdministradorControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarAdministradorDto)
  }
);}





export const getAdministradorControllerCriarMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof administradorControllerCriar>>, TError,AdministradorControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof administradorControllerCriar>>, TError,AdministradorControllerCriarMutationVariables, TContext> => {

const mutationKey = ['administradorControllerCriar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof administradorControllerCriar>>, AdministradorControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  administradorControllerCriar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdministradorControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof administradorControllerCriar>>>
    export type AdministradorControllerCriarMutationBody = CriarAdministradorDto
    export type AdministradorControllerCriarMutationError = ErroRespostaDto
    export type AdministradorControllerCriarMutationVariables = {data: CriarAdministradorDto}

    /**
 * @summary Cria um administrador
 */
export const useAdministradorControllerCriar = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof administradorControllerCriar>>, TError,AdministradorControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof administradorControllerCriar>>,
        TError,
        AdministradorControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getAdministradorControllerCriarMutationOptions(options), queryClient);
    }
    export type administradorControllerListarResponse200 = {
  data: void
  status: 200
}

export type administradorControllerListarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type administradorControllerListarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type administradorControllerListarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type administradorControllerListarResponseSuccess = (administradorControllerListarResponse200) & {
  headers: Headers;
};
export type administradorControllerListarResponseError = (administradorControllerListarResponse400 | administradorControllerListarResponse404 | administradorControllerListarResponse409) & {
  headers: Headers;
};

export type administradorControllerListarResponse = (administradorControllerListarResponseSuccess | administradorControllerListarResponseError)

export const getAdministradorControllerListarUrl = (params?: AdministradorControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/administradores?${stringifiedParams}` : `${apiBaseUrl}/administradores`
}

/**
 * @summary Lista os administradores de forma paginada
 */
export const administradorControllerListar = async (params?: AdministradorControllerListarParams, options?: Parameters<typeof httpClient>[1]): Promise<administradorControllerListarResponse> => {

  return httpClient<administradorControllerListarResponse>(getAdministradorControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdministradorControllerListarQueryKey = (params?: AdministradorControllerListarParams,) => {
    return [
    `${apiBaseUrl}/administradores`, ...(params ? [params] : [])
    ] as const;
    }


export const getAdministradorControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof administradorControllerListar>>, TError = ErroRespostaDto>(params?: AdministradorControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdministradorControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof administradorControllerListar>>> = ({ signal }) => administradorControllerListar(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof administradorControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdministradorControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof administradorControllerListar>>>
export type AdministradorControllerListarQueryError = ErroRespostaDto


export function useAdministradorControllerListar<TData = Awaited<ReturnType<typeof administradorControllerListar>>, TError = ErroRespostaDto>(
 params: undefined |  AdministradorControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof administradorControllerListar>>,
          TError,
          Awaited<ReturnType<typeof administradorControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdministradorControllerListar<TData = Awaited<ReturnType<typeof administradorControllerListar>>, TError = ErroRespostaDto>(
 params?: AdministradorControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof administradorControllerListar>>,
          TError,
          Awaited<ReturnType<typeof administradorControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdministradorControllerListar<TData = Awaited<ReturnType<typeof administradorControllerListar>>, TError = ErroRespostaDto>(
 params?: AdministradorControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista os administradores de forma paginada
 */

export function useAdministradorControllerListar<TData = Awaited<ReturnType<typeof administradorControllerListar>>, TError = ErroRespostaDto>(
 params?: AdministradorControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdministradorControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type administradorControllerBuscarResponse200 = {
  data: void
  status: 200
}

export type administradorControllerBuscarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type administradorControllerBuscarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type administradorControllerBuscarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type administradorControllerBuscarResponseSuccess = (administradorControllerBuscarResponse200) & {
  headers: Headers;
};
export type administradorControllerBuscarResponseError = (administradorControllerBuscarResponse400 | administradorControllerBuscarResponse404 | administradorControllerBuscarResponse409) & {
  headers: Headers;
};

export type administradorControllerBuscarResponse = (administradorControllerBuscarResponseSuccess | administradorControllerBuscarResponseError)

export const getAdministradorControllerBuscarUrl = (id: number,) => {




  return `${apiBaseUrl}/administradores/${id}`
}

/**
 * @summary Busca um administrador pelo identificador
 */
export const administradorControllerBuscar = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<administradorControllerBuscarResponse> => {

  return httpClient<administradorControllerBuscarResponse>(getAdministradorControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAdministradorControllerBuscarQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/administradores/${id}`
    ] as const;
    }


export const getAdministradorControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof administradorControllerBuscar>>, TError = ErroRespostaDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdministradorControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof administradorControllerBuscar>>> = ({ signal }) => administradorControllerBuscar(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof administradorControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdministradorControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof administradorControllerBuscar>>>
export type AdministradorControllerBuscarQueryError = ErroRespostaDto


export function useAdministradorControllerBuscar<TData = Awaited<ReturnType<typeof administradorControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof administradorControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof administradorControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdministradorControllerBuscar<TData = Awaited<ReturnType<typeof administradorControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof administradorControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof administradorControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdministradorControllerBuscar<TData = Awaited<ReturnType<typeof administradorControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Busca um administrador pelo identificador
 */

export function useAdministradorControllerBuscar<TData = Awaited<ReturnType<typeof administradorControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof administradorControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdministradorControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type administradorControllerAtualizarResponse200 = {
  data: void
  status: 200
}

export type administradorControllerAtualizarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type administradorControllerAtualizarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type administradorControllerAtualizarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type administradorControllerAtualizarResponseSuccess = (administradorControllerAtualizarResponse200) & {
  headers: Headers;
};
export type administradorControllerAtualizarResponseError = (administradorControllerAtualizarResponse400 | administradorControllerAtualizarResponse404 | administradorControllerAtualizarResponse409) & {
  headers: Headers;
};

export type administradorControllerAtualizarResponse = (administradorControllerAtualizarResponseSuccess | administradorControllerAtualizarResponseError)

export const getAdministradorControllerAtualizarUrl = (id: number,) => {




  return `${apiBaseUrl}/administradores/${id}`
}

/**
 * @summary Atualiza um administrador pelo identificador
 */
export const administradorControllerAtualizar = async (id: number,
    atualizarAdministradorDto: AtualizarAdministradorDto, options?: Parameters<typeof httpClient>[1]): Promise<administradorControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<administradorControllerAtualizarResponse>(getAdministradorControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarAdministradorDto)
  }
);}





export const getAdministradorControllerAtualizarMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof administradorControllerAtualizar>>, TError,AdministradorControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof administradorControllerAtualizar>>, TError,AdministradorControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['administradorControllerAtualizar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof administradorControllerAtualizar>>, AdministradorControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  administradorControllerAtualizar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdministradorControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof administradorControllerAtualizar>>>
    export type AdministradorControllerAtualizarMutationBody = AtualizarAdministradorDto
    export type AdministradorControllerAtualizarMutationError = ErroRespostaDto
    export type AdministradorControllerAtualizarMutationVariables = {id: number;data: AtualizarAdministradorDto}

    /**
 * @summary Atualiza um administrador pelo identificador
 */
export const useAdministradorControllerAtualizar = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof administradorControllerAtualizar>>, TError,AdministradorControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof administradorControllerAtualizar>>,
        TError,
        AdministradorControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getAdministradorControllerAtualizarMutationOptions(options), queryClient);
    }
    export type administradorControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type administradorControllerRemoverResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type administradorControllerRemoverResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type administradorControllerRemoverResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type administradorControllerRemoverResponseSuccess = (administradorControllerRemoverResponse200) & {
  headers: Headers;
};
export type administradorControllerRemoverResponseError = (administradorControllerRemoverResponse400 | administradorControllerRemoverResponse404 | administradorControllerRemoverResponse409) & {
  headers: Headers;
};

export type administradorControllerRemoverResponse = (administradorControllerRemoverResponseSuccess | administradorControllerRemoverResponseError)

export const getAdministradorControllerRemoverUrl = (id: number,) => {




  return `${apiBaseUrl}/administradores/${id}`
}

/**
 * @summary Remove um administrador pelo identificador
 */
export const administradorControllerRemover = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<administradorControllerRemoverResponse> => {

  return httpClient<administradorControllerRemoverResponse>(getAdministradorControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getAdministradorControllerRemoverMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof administradorControllerRemover>>, TError,AdministradorControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof administradorControllerRemover>>, TError,AdministradorControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['administradorControllerRemover'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof administradorControllerRemover>>, AdministradorControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  administradorControllerRemover(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AdministradorControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof administradorControllerRemover>>>

    export type AdministradorControllerRemoverMutationError = ErroRespostaDto
    export type AdministradorControllerRemoverMutationVariables = {id: number}

    /**
 * @summary Remove um administrador pelo identificador
 */
export const useAdministradorControllerRemover = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof administradorControllerRemover>>, TError,AdministradorControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof administradorControllerRemover>>,
        TError,
        AdministradorControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getAdministradorControllerRemoverMutationOptions(options), queryClient);
    }
