/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AtualizarBarbeiroDto,
  BarbeiroControllerListarParams,
  BarbeiroRespostaDto,
  CriarBarbeiroDto,
  ErroRespostaDto,
  ListaBarbeirosRespostaDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type barbeiroControllerCriarResponse201 = {
  data: BarbeiroRespostaDto
  status: 201
}

export type barbeiroControllerCriarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type barbeiroControllerCriarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type barbeiroControllerCriarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type barbeiroControllerCriarResponseSuccess = (barbeiroControllerCriarResponse201) & {
  headers: Headers;
};
export type barbeiroControllerCriarResponseError = (barbeiroControllerCriarResponse400 | barbeiroControllerCriarResponse404 | barbeiroControllerCriarResponse409) & {
  headers: Headers;
};

export type barbeiroControllerCriarResponse = (barbeiroControllerCriarResponseSuccess | barbeiroControllerCriarResponseError)

export const getBarbeiroControllerCriarUrl = () => {




  return `${apiBaseUrl}/barbeiros`
}

/**
 * @summary Cria um barbeiro
 */
export const barbeiroControllerCriar = async (criarBarbeiroDto: CriarBarbeiroDto, options?: Parameters<typeof httpClient>[1]): Promise<barbeiroControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<barbeiroControllerCriarResponse>(getBarbeiroControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarBarbeiroDto)
  }
);}





export const getBarbeiroControllerCriarMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerCriar>>, TError,BarbeiroControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerCriar>>, TError,BarbeiroControllerCriarMutationVariables, TContext> => {

const mutationKey = ['barbeiroControllerCriar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof barbeiroControllerCriar>>, BarbeiroControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  barbeiroControllerCriar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BarbeiroControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerCriar>>>
    export type BarbeiroControllerCriarMutationBody = CriarBarbeiroDto
    export type BarbeiroControllerCriarMutationError = ErroRespostaDto
    export type BarbeiroControllerCriarMutationVariables = {data: CriarBarbeiroDto}

    /**
 * @summary Cria um barbeiro
 */
export const useBarbeiroControllerCriar = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerCriar>>, TError,BarbeiroControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof barbeiroControllerCriar>>,
        TError,
        BarbeiroControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getBarbeiroControllerCriarMutationOptions(options), queryClient);
    }
    export type barbeiroControllerListarResponse200 = {
  data: ListaBarbeirosRespostaDto
  status: 200
}

export type barbeiroControllerListarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type barbeiroControllerListarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type barbeiroControllerListarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type barbeiroControllerListarResponseSuccess = (barbeiroControllerListarResponse200) & {
  headers: Headers;
};
export type barbeiroControllerListarResponseError = (barbeiroControllerListarResponse400 | barbeiroControllerListarResponse404 | barbeiroControllerListarResponse409) & {
  headers: Headers;
};

export type barbeiroControllerListarResponse = (barbeiroControllerListarResponseSuccess | barbeiroControllerListarResponseError)

export const getBarbeiroControllerListarUrl = (params?: BarbeiroControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/barbeiros?${stringifiedParams}` : `${apiBaseUrl}/barbeiros`
}

/**
 * @summary Lista os barbeiros de forma paginada
 */
export const barbeiroControllerListar = async (params?: BarbeiroControllerListarParams, options?: Parameters<typeof httpClient>[1]): Promise<barbeiroControllerListarResponse> => {

  return httpClient<barbeiroControllerListarResponse>(getBarbeiroControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBarbeiroControllerListarQueryKey = (params?: BarbeiroControllerListarParams,) => {
    return [
    `${apiBaseUrl}/barbeiros`, ...(params ? [params] : [])
    ] as const;
    }


export const getBarbeiroControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = ErroRespostaDto>(params?: BarbeiroControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBarbeiroControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof barbeiroControllerListar>>> = ({ signal }) => barbeiroControllerListar(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BarbeiroControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerListar>>>
export type BarbeiroControllerListarQueryError = ErroRespostaDto


export function useBarbeiroControllerListar<TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = ErroRespostaDto>(
 params: undefined |  BarbeiroControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof barbeiroControllerListar>>,
          TError,
          Awaited<ReturnType<typeof barbeiroControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBarbeiroControllerListar<TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = ErroRespostaDto>(
 params?: BarbeiroControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof barbeiroControllerListar>>,
          TError,
          Awaited<ReturnType<typeof barbeiroControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBarbeiroControllerListar<TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = ErroRespostaDto>(
 params?: BarbeiroControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lista os barbeiros de forma paginada
 */

export function useBarbeiroControllerListar<TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = ErroRespostaDto>(
 params?: BarbeiroControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBarbeiroControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type barbeiroControllerBuscarResponse200 = {
  data: BarbeiroRespostaDto
  status: 200
}

export type barbeiroControllerBuscarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type barbeiroControllerBuscarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type barbeiroControllerBuscarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type barbeiroControllerBuscarResponseSuccess = (barbeiroControllerBuscarResponse200) & {
  headers: Headers;
};
export type barbeiroControllerBuscarResponseError = (barbeiroControllerBuscarResponse400 | barbeiroControllerBuscarResponse404 | barbeiroControllerBuscarResponse409) & {
  headers: Headers;
};

export type barbeiroControllerBuscarResponse = (barbeiroControllerBuscarResponseSuccess | barbeiroControllerBuscarResponseError)

export const getBarbeiroControllerBuscarUrl = (id: number,) => {




  return `${apiBaseUrl}/barbeiros/${id}`
}

/**
 * @summary Busca um barbeiro pelo identificador
 */
export const barbeiroControllerBuscar = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<barbeiroControllerBuscarResponse> => {

  return httpClient<barbeiroControllerBuscarResponse>(getBarbeiroControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getBarbeiroControllerBuscarQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/barbeiros/${id}`
    ] as const;
    }


export const getBarbeiroControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = ErroRespostaDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBarbeiroControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof barbeiroControllerBuscar>>> = ({ signal }) => barbeiroControllerBuscar(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BarbeiroControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerBuscar>>>
export type BarbeiroControllerBuscarQueryError = ErroRespostaDto


export function useBarbeiroControllerBuscar<TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof barbeiroControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof barbeiroControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBarbeiroControllerBuscar<TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof barbeiroControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof barbeiroControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBarbeiroControllerBuscar<TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Busca um barbeiro pelo identificador
 */

export function useBarbeiroControllerBuscar<TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = ErroRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBarbeiroControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type barbeiroControllerAtualizarResponse200 = {
  data: BarbeiroRespostaDto
  status: 200
}

export type barbeiroControllerAtualizarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type barbeiroControllerAtualizarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type barbeiroControllerAtualizarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type barbeiroControllerAtualizarResponseSuccess = (barbeiroControllerAtualizarResponse200) & {
  headers: Headers;
};
export type barbeiroControllerAtualizarResponseError = (barbeiroControllerAtualizarResponse400 | barbeiroControllerAtualizarResponse404 | barbeiroControllerAtualizarResponse409) & {
  headers: Headers;
};

export type barbeiroControllerAtualizarResponse = (barbeiroControllerAtualizarResponseSuccess | barbeiroControllerAtualizarResponseError)

export const getBarbeiroControllerAtualizarUrl = (id: number,) => {




  return `${apiBaseUrl}/barbeiros/${id}`
}

/**
 * @summary Atualiza um barbeiro pelo identificador
 */
export const barbeiroControllerAtualizar = async (id: number,
    atualizarBarbeiroDto: AtualizarBarbeiroDto, options?: Parameters<typeof httpClient>[1]): Promise<barbeiroControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<barbeiroControllerAtualizarResponse>(getBarbeiroControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarBarbeiroDto)
  }
);}





export const getBarbeiroControllerAtualizarMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>, TError,BarbeiroControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>, TError,BarbeiroControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['barbeiroControllerAtualizar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>, BarbeiroControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  barbeiroControllerAtualizar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BarbeiroControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>>
    export type BarbeiroControllerAtualizarMutationBody = AtualizarBarbeiroDto
    export type BarbeiroControllerAtualizarMutationError = ErroRespostaDto
    export type BarbeiroControllerAtualizarMutationVariables = {id: number;data: AtualizarBarbeiroDto}

    /**
 * @summary Atualiza um barbeiro pelo identificador
 */
export const useBarbeiroControllerAtualizar = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>, TError,BarbeiroControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof barbeiroControllerAtualizar>>,
        TError,
        BarbeiroControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getBarbeiroControllerAtualizarMutationOptions(options), queryClient);
    }
    export type barbeiroControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type barbeiroControllerRemoverResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type barbeiroControllerRemoverResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type barbeiroControllerRemoverResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type barbeiroControllerRemoverResponseSuccess = (barbeiroControllerRemoverResponse200) & {
  headers: Headers;
};
export type barbeiroControllerRemoverResponseError = (barbeiroControllerRemoverResponse400 | barbeiroControllerRemoverResponse404 | barbeiroControllerRemoverResponse409) & {
  headers: Headers;
};

export type barbeiroControllerRemoverResponse = (barbeiroControllerRemoverResponseSuccess | barbeiroControllerRemoverResponseError)

export const getBarbeiroControllerRemoverUrl = (id: number,) => {




  return `${apiBaseUrl}/barbeiros/${id}`
}

/**
 * @summary Remove um barbeiro pelo identificador
 */
export const barbeiroControllerRemover = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<barbeiroControllerRemoverResponse> => {

  return httpClient<barbeiroControllerRemoverResponse>(getBarbeiroControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getBarbeiroControllerRemoverMutationOptions = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerRemover>>, TError,BarbeiroControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerRemover>>, TError,BarbeiroControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['barbeiroControllerRemover'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof barbeiroControllerRemover>>, BarbeiroControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  barbeiroControllerRemover(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BarbeiroControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerRemover>>>

    export type BarbeiroControllerRemoverMutationError = ErroRespostaDto
    export type BarbeiroControllerRemoverMutationVariables = {id: number}

    /**
 * @summary Remove um barbeiro pelo identificador
 */
export const useBarbeiroControllerRemover = <TError = ErroRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerRemover>>, TError,BarbeiroControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof barbeiroControllerRemover>>,
        TError,
        BarbeiroControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getBarbeiroControllerRemoverMutationOptions(options), queryClient);
    }
