/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AtualizarBarbeiroDto,
  BarbeiroControllerListarParams,
  CriarBarbeiroDto
} from '../models';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type barbeiroControllerCriarResponse201 = {
  data: void
  status: 201
}

export type barbeiroControllerCriarResponseSuccess = (barbeiroControllerCriarResponse201) & {
  headers: Headers;
};
;

export type barbeiroControllerCriarResponse = (barbeiroControllerCriarResponseSuccess)

export const getBarbeiroControllerCriarUrl = () => {




  return `/barbeiros`
}

export const barbeiroControllerCriar = async (criarBarbeiroDto: CriarBarbeiroDto, options?: RequestInit): Promise<barbeiroControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getBarbeiroControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarBarbeiroDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: barbeiroControllerCriarResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as barbeiroControllerCriarResponse
}





export const getBarbeiroControllerCriarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerCriar>>, TError,BarbeiroControllerCriarMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerCriar>>, TError,BarbeiroControllerCriarMutationVariables, TContext> => {

const mutationKey = ['barbeiroControllerCriar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof barbeiroControllerCriar>>, BarbeiroControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  barbeiroControllerCriar(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BarbeiroControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerCriar>>>
    export type BarbeiroControllerCriarMutationBody = CriarBarbeiroDto
    export type BarbeiroControllerCriarMutationError = unknown
    export type BarbeiroControllerCriarMutationVariables = {data: CriarBarbeiroDto}

    export const useBarbeiroControllerCriar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerCriar>>, TError,BarbeiroControllerCriarMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof barbeiroControllerCriar>>,
        TError,
        BarbeiroControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getBarbeiroControllerCriarMutationOptions(options), queryClient);
    }
    export type barbeiroControllerListarResponse200 = {
  data: void
  status: 200
}

export type barbeiroControllerListarResponseSuccess = (barbeiroControllerListarResponse200) & {
  headers: Headers;
};
;

export type barbeiroControllerListarResponse = (barbeiroControllerListarResponseSuccess)

export const getBarbeiroControllerListarUrl = (params: BarbeiroControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/barbeiros?${stringifiedParams}` : `/barbeiros`
}

export const barbeiroControllerListar = async (params: BarbeiroControllerListarParams, options?: RequestInit): Promise<barbeiroControllerListarResponse> => {

  const res = await fetch(getBarbeiroControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: barbeiroControllerListarResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as barbeiroControllerListarResponse
}





export const getBarbeiroControllerListarQueryKey = (params?: BarbeiroControllerListarParams,) => {
    return [
    `/barbeiros`, ...(params ? [params] : [])
    ] as const;
    }


export const getBarbeiroControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = unknown>(params: BarbeiroControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBarbeiroControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof barbeiroControllerListar>>> = ({ signal }) => barbeiroControllerListar(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BarbeiroControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerListar>>>
export type BarbeiroControllerListarQueryError = unknown


export function useBarbeiroControllerListar<TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = unknown>(
 params: BarbeiroControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof barbeiroControllerListar>>,
          TError,
          Awaited<ReturnType<typeof barbeiroControllerListar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBarbeiroControllerListar<TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = unknown>(
 params: BarbeiroControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof barbeiroControllerListar>>,
          TError,
          Awaited<ReturnType<typeof barbeiroControllerListar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBarbeiroControllerListar<TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = unknown>(
 params: BarbeiroControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBarbeiroControllerListar<TData = Awaited<ReturnType<typeof barbeiroControllerListar>>, TError = unknown>(
 params: BarbeiroControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerListar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBarbeiroControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type barbeiroControllerBuscarResponse200 = {
  data: void
  status: 200
}

export type barbeiroControllerBuscarResponseSuccess = (barbeiroControllerBuscarResponse200) & {
  headers: Headers;
};
;

export type barbeiroControllerBuscarResponse = (barbeiroControllerBuscarResponseSuccess)

export const getBarbeiroControllerBuscarUrl = (id: number,) => {




  return `/barbeiros/${id}`
}

export const barbeiroControllerBuscar = async (id: number, options?: RequestInit): Promise<barbeiroControllerBuscarResponse> => {

  const res = await fetch(getBarbeiroControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: barbeiroControllerBuscarResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as barbeiroControllerBuscarResponse
}





export const getBarbeiroControllerBuscarQueryKey = (id: number,) => {
    return [
    `/barbeiros/${id}`
    ] as const;
    }


export const getBarbeiroControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBarbeiroControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof barbeiroControllerBuscar>>> = ({ signal }) => barbeiroControllerBuscar(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BarbeiroControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerBuscar>>>
export type BarbeiroControllerBuscarQueryError = unknown


export function useBarbeiroControllerBuscar<TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof barbeiroControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof barbeiroControllerBuscar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBarbeiroControllerBuscar<TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof barbeiroControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof barbeiroControllerBuscar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBarbeiroControllerBuscar<TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useBarbeiroControllerBuscar<TData = Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof barbeiroControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBarbeiroControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type barbeiroControllerAtualizarResponse200 = {
  data: void
  status: 200
}

export type barbeiroControllerAtualizarResponseSuccess = (barbeiroControllerAtualizarResponse200) & {
  headers: Headers;
};
;

export type barbeiroControllerAtualizarResponse = (barbeiroControllerAtualizarResponseSuccess)

export const getBarbeiroControllerAtualizarUrl = (id: number,) => {




  return `/barbeiros/${id}`
}

export const barbeiroControllerAtualizar = async (id: number,
    atualizarBarbeiroDto: AtualizarBarbeiroDto, options?: RequestInit): Promise<barbeiroControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getBarbeiroControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarBarbeiroDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: barbeiroControllerAtualizarResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as barbeiroControllerAtualizarResponse
}





export const getBarbeiroControllerAtualizarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>, TError,BarbeiroControllerAtualizarMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>, TError,BarbeiroControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['barbeiroControllerAtualizar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>, BarbeiroControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  barbeiroControllerAtualizar(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BarbeiroControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>>
    export type BarbeiroControllerAtualizarMutationBody = AtualizarBarbeiroDto
    export type BarbeiroControllerAtualizarMutationError = unknown
    export type BarbeiroControllerAtualizarMutationVariables = {id: number;data: AtualizarBarbeiroDto}

    export const useBarbeiroControllerAtualizar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerAtualizar>>, TError,BarbeiroControllerAtualizarMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof barbeiroControllerAtualizar>>,
        TError,
        BarbeiroControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getBarbeiroControllerAtualizarMutationOptions(options), queryClient);
    }
    export type barbeiroControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type barbeiroControllerRemoverResponseSuccess = (barbeiroControllerRemoverResponse200) & {
  headers: Headers;
};
;

export type barbeiroControllerRemoverResponse = (barbeiroControllerRemoverResponseSuccess)

export const getBarbeiroControllerRemoverUrl = (id: number,) => {




  return `/barbeiros/${id}`
}

export const barbeiroControllerRemover = async (id: number, options?: RequestInit): Promise<barbeiroControllerRemoverResponse> => {

  const res = await fetch(getBarbeiroControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: barbeiroControllerRemoverResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as barbeiroControllerRemoverResponse
}





export const getBarbeiroControllerRemoverMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerRemover>>, TError,BarbeiroControllerRemoverMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerRemover>>, TError,BarbeiroControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['barbeiroControllerRemover'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof barbeiroControllerRemover>>, BarbeiroControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  barbeiroControllerRemover(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BarbeiroControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof barbeiroControllerRemover>>>

    export type BarbeiroControllerRemoverMutationError = unknown
    export type BarbeiroControllerRemoverMutationVariables = {id: number}

    export const useBarbeiroControllerRemover = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof barbeiroControllerRemover>>, TError,BarbeiroControllerRemoverMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof barbeiroControllerRemover>>,
        TError,
        BarbeiroControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getBarbeiroControllerRemoverMutationOptions(options), queryClient);
    }
