/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AtualizarPermissaoDto,
  CriarPermissaoDto,
  ErroRespostaDto,
  LimiteRequisicoesRespostaDto,
  PermissaoControllerListarParams
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type permissaoControllerCriarResponse201 = {
  data: void
  status: 201
}

export type permissaoControllerCriarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type permissaoControllerCriarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type permissaoControllerCriarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type permissaoControllerCriarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type permissaoControllerCriarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type permissaoControllerCriarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type permissaoControllerCriarResponseSuccess = (permissaoControllerCriarResponse201) & {
  headers: Headers;
};
export type permissaoControllerCriarResponseError = (permissaoControllerCriarResponse400 | permissaoControllerCriarResponse401 | permissaoControllerCriarResponse403 | permissaoControllerCriarResponse404 | permissaoControllerCriarResponse409 | permissaoControllerCriarResponse429) & {
  headers: Headers;
};

export type permissaoControllerCriarResponse = (permissaoControllerCriarResponseSuccess | permissaoControllerCriarResponseError)

export const getPermissaoControllerCriarUrl = () => {




  return `${apiBaseUrl}/permissoes`
}

export const permissaoControllerCriar = async (criarPermissaoDto: CriarPermissaoDto, options?: Parameters<typeof httpClient>[1]): Promise<permissaoControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<permissaoControllerCriarResponse>(getPermissaoControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarPermissaoDto)
  }
);}





export const getPermissaoControllerCriarMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof permissaoControllerCriar>>, TError,PermissaoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof permissaoControllerCriar>>, TError,PermissaoControllerCriarMutationVariables, TContext> => {

const mutationKey = ['permissaoControllerCriar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof permissaoControllerCriar>>, PermissaoControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  permissaoControllerCriar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PermissaoControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof permissaoControllerCriar>>>
    export type PermissaoControllerCriarMutationBody = CriarPermissaoDto
    export type PermissaoControllerCriarMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type PermissaoControllerCriarMutationVariables = {data: CriarPermissaoDto}

    export const usePermissaoControllerCriar = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof permissaoControllerCriar>>, TError,PermissaoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof permissaoControllerCriar>>,
        TError,
        PermissaoControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getPermissaoControllerCriarMutationOptions(options), queryClient);
    }
    export type permissaoControllerListarResponse200 = {
  data: void
  status: 200
}

export type permissaoControllerListarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type permissaoControllerListarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type permissaoControllerListarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type permissaoControllerListarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type permissaoControllerListarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type permissaoControllerListarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type permissaoControllerListarResponseSuccess = (permissaoControllerListarResponse200) & {
  headers: Headers;
};
export type permissaoControllerListarResponseError = (permissaoControllerListarResponse400 | permissaoControllerListarResponse401 | permissaoControllerListarResponse403 | permissaoControllerListarResponse404 | permissaoControllerListarResponse409 | permissaoControllerListarResponse429) & {
  headers: Headers;
};

export type permissaoControllerListarResponse = (permissaoControllerListarResponseSuccess | permissaoControllerListarResponseError)

export const getPermissaoControllerListarUrl = (params?: PermissaoControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/permissoes?${stringifiedParams}` : `${apiBaseUrl}/permissoes`
}

export const permissaoControllerListar = async (params?: PermissaoControllerListarParams, options?: Parameters<typeof httpClient>[1]): Promise<permissaoControllerListarResponse> => {

  return httpClient<permissaoControllerListarResponse>(getPermissaoControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPermissaoControllerListarQueryKey = (params?: PermissaoControllerListarParams,) => {
    return [
    `${apiBaseUrl}/permissoes`, ...(params ? [params] : [])
    ] as const;
    }


export const getPermissaoControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof permissaoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(params?: PermissaoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPermissaoControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof permissaoControllerListar>>> = ({ signal }) => permissaoControllerListar(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PermissaoControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof permissaoControllerListar>>>
export type PermissaoControllerListarQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function usePermissaoControllerListar<TData = Awaited<ReturnType<typeof permissaoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: undefined |  PermissaoControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof permissaoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof permissaoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePermissaoControllerListar<TData = Awaited<ReturnType<typeof permissaoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: PermissaoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof permissaoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof permissaoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePermissaoControllerListar<TData = Awaited<ReturnType<typeof permissaoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: PermissaoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePermissaoControllerListar<TData = Awaited<ReturnType<typeof permissaoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: PermissaoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPermissaoControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type permissaoControllerBuscarResponse200 = {
  data: void
  status: 200
}

export type permissaoControllerBuscarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type permissaoControllerBuscarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type permissaoControllerBuscarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type permissaoControllerBuscarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type permissaoControllerBuscarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type permissaoControllerBuscarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type permissaoControllerBuscarResponseSuccess = (permissaoControllerBuscarResponse200) & {
  headers: Headers;
};
export type permissaoControllerBuscarResponseError = (permissaoControllerBuscarResponse400 | permissaoControllerBuscarResponse401 | permissaoControllerBuscarResponse403 | permissaoControllerBuscarResponse404 | permissaoControllerBuscarResponse409 | permissaoControllerBuscarResponse429) & {
  headers: Headers;
};

export type permissaoControllerBuscarResponse = (permissaoControllerBuscarResponseSuccess | permissaoControllerBuscarResponseError)

export const getPermissaoControllerBuscarUrl = (id: number,) => {




  return `${apiBaseUrl}/permissoes/${id}`
}

export const permissaoControllerBuscar = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<permissaoControllerBuscarResponse> => {

  return httpClient<permissaoControllerBuscarResponse>(getPermissaoControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPermissaoControllerBuscarQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/permissoes/${id}`
    ] as const;
    }


export const getPermissaoControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPermissaoControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof permissaoControllerBuscar>>> = ({ signal }) => permissaoControllerBuscar(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PermissaoControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof permissaoControllerBuscar>>>
export type PermissaoControllerBuscarQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function usePermissaoControllerBuscar<TData = Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof permissaoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof permissaoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePermissaoControllerBuscar<TData = Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof permissaoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof permissaoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePermissaoControllerBuscar<TData = Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePermissaoControllerBuscar<TData = Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof permissaoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPermissaoControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type permissaoControllerAtualizarResponse200 = {
  data: void
  status: 200
}

export type permissaoControllerAtualizarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type permissaoControllerAtualizarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type permissaoControllerAtualizarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type permissaoControllerAtualizarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type permissaoControllerAtualizarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type permissaoControllerAtualizarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type permissaoControllerAtualizarResponseSuccess = (permissaoControllerAtualizarResponse200) & {
  headers: Headers;
};
export type permissaoControllerAtualizarResponseError = (permissaoControllerAtualizarResponse400 | permissaoControllerAtualizarResponse401 | permissaoControllerAtualizarResponse403 | permissaoControllerAtualizarResponse404 | permissaoControllerAtualizarResponse409 | permissaoControllerAtualizarResponse429) & {
  headers: Headers;
};

export type permissaoControllerAtualizarResponse = (permissaoControllerAtualizarResponseSuccess | permissaoControllerAtualizarResponseError)

export const getPermissaoControllerAtualizarUrl = (id: number,) => {




  return `${apiBaseUrl}/permissoes/${id}`
}

export const permissaoControllerAtualizar = async (id: number,
    atualizarPermissaoDto: AtualizarPermissaoDto, options?: Parameters<typeof httpClient>[1]): Promise<permissaoControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<permissaoControllerAtualizarResponse>(getPermissaoControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarPermissaoDto)
  }
);}





export const getPermissaoControllerAtualizarMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof permissaoControllerAtualizar>>, TError,PermissaoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof permissaoControllerAtualizar>>, TError,PermissaoControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['permissaoControllerAtualizar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof permissaoControllerAtualizar>>, PermissaoControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  permissaoControllerAtualizar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PermissaoControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof permissaoControllerAtualizar>>>
    export type PermissaoControllerAtualizarMutationBody = AtualizarPermissaoDto
    export type PermissaoControllerAtualizarMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type PermissaoControllerAtualizarMutationVariables = {id: number;data: AtualizarPermissaoDto}

    export const usePermissaoControllerAtualizar = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof permissaoControllerAtualizar>>, TError,PermissaoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof permissaoControllerAtualizar>>,
        TError,
        PermissaoControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getPermissaoControllerAtualizarMutationOptions(options), queryClient);
    }
    export type permissaoControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type permissaoControllerRemoverResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type permissaoControllerRemoverResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type permissaoControllerRemoverResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type permissaoControllerRemoverResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type permissaoControllerRemoverResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type permissaoControllerRemoverResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type permissaoControllerRemoverResponseSuccess = (permissaoControllerRemoverResponse200) & {
  headers: Headers;
};
export type permissaoControllerRemoverResponseError = (permissaoControllerRemoverResponse400 | permissaoControllerRemoverResponse401 | permissaoControllerRemoverResponse403 | permissaoControllerRemoverResponse404 | permissaoControllerRemoverResponse409 | permissaoControllerRemoverResponse429) & {
  headers: Headers;
};

export type permissaoControllerRemoverResponse = (permissaoControllerRemoverResponseSuccess | permissaoControllerRemoverResponseError)

export const getPermissaoControllerRemoverUrl = (id: number,) => {




  return `${apiBaseUrl}/permissoes/${id}`
}

export const permissaoControllerRemover = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<permissaoControllerRemoverResponse> => {

  return httpClient<permissaoControllerRemoverResponse>(getPermissaoControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getPermissaoControllerRemoverMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof permissaoControllerRemover>>, TError,PermissaoControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof permissaoControllerRemover>>, TError,PermissaoControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['permissaoControllerRemover'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof permissaoControllerRemover>>, PermissaoControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  permissaoControllerRemover(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PermissaoControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof permissaoControllerRemover>>>

    export type PermissaoControllerRemoverMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type PermissaoControllerRemoverMutationVariables = {id: number}

    export const usePermissaoControllerRemover = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof permissaoControllerRemover>>, TError,PermissaoControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof permissaoControllerRemover>>,
        TError,
        PermissaoControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getPermissaoControllerRemoverMutationOptions(options), queryClient);
    }
