/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AgendamentoControllerAtualizar200,
  AgendamentoControllerBuscar200,
  AgendamentoControllerCriar201,
  AgendamentoControllerCriarHistorico201,
  AgendamentoControllerListar200,
  AgendamentoControllerListarHistorico200,
  AgendamentoControllerListarHistoricoParams,
  AgendamentoControllerListarParams,
  AtualizarAgendamentoDto,
  CriarAgendamentoDto,
  CriarHistoricoStatusDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type agendamentoControllerCriarResponse201 = {
  data: AgendamentoControllerCriar201
  status: 201
}

export type agendamentoControllerCriarResponseSuccess = (agendamentoControllerCriarResponse201) & {
  headers: Headers;
};
;

export type agendamentoControllerCriarResponse = (agendamentoControllerCriarResponseSuccess)

export const getAgendamentoControllerCriarUrl = () => {




  return `${apiBaseUrl}/agendamentos`
}

export const agendamentoControllerCriar = async (criarAgendamentoDto: CriarAgendamentoDto, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<agendamentoControllerCriarResponse>(getAgendamentoControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarAgendamentoDto)
  }
);}





export const getAgendamentoControllerCriarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriar>>, TError,AgendamentoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriar>>, TError,AgendamentoControllerCriarMutationVariables, TContext> => {

const mutationKey = ['agendamentoControllerCriar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof agendamentoControllerCriar>>, AgendamentoControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  agendamentoControllerCriar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AgendamentoControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerCriar>>>
    export type AgendamentoControllerCriarMutationBody = CriarAgendamentoDto
    export type AgendamentoControllerCriarMutationError = unknown
    export type AgendamentoControllerCriarMutationVariables = {data: CriarAgendamentoDto}

    export const useAgendamentoControllerCriar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriar>>, TError,AgendamentoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof agendamentoControllerCriar>>,
        TError,
        AgendamentoControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getAgendamentoControllerCriarMutationOptions(options), queryClient);
    }
    export type agendamentoControllerListarResponse200 = {
  data: AgendamentoControllerListar200
  status: 200
}

export type agendamentoControllerListarResponseSuccess = (agendamentoControllerListarResponse200) & {
  headers: Headers;
};
;

export type agendamentoControllerListarResponse = (agendamentoControllerListarResponseSuccess)

export const getAgendamentoControllerListarUrl = (params?: AgendamentoControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/agendamentos?${stringifiedParams}` : `${apiBaseUrl}/agendamentos`
}

export const agendamentoControllerListar = async (params?: AgendamentoControllerListarParams, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerListarResponse> => {

  return httpClient<agendamentoControllerListarResponse>(getAgendamentoControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAgendamentoControllerListarQueryKey = (params?: AgendamentoControllerListarParams,) => {
    return [
    `${apiBaseUrl}/agendamentos`, ...(params ? [params] : [])
    ] as const;
    }


export const getAgendamentoControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = unknown>(params?: AgendamentoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAgendamentoControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof agendamentoControllerListar>>> = ({ signal }) => agendamentoControllerListar(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerListar>>>
export type AgendamentoControllerListarQueryError = unknown


export function useAgendamentoControllerListar<TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = unknown>(
 params: undefined |  AgendamentoControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerListar<TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = unknown>(
 params?: AgendamentoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerListar<TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = unknown>(
 params?: AgendamentoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAgendamentoControllerListar<TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = unknown>(
 params?: AgendamentoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAgendamentoControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type agendamentoControllerListarHistoricoResponse200 = {
  data: AgendamentoControllerListarHistorico200
  status: 200
}

export type agendamentoControllerListarHistoricoResponseSuccess = (agendamentoControllerListarHistoricoResponse200) & {
  headers: Headers;
};
;

export type agendamentoControllerListarHistoricoResponse = (agendamentoControllerListarHistoricoResponseSuccess)

export const getAgendamentoControllerListarHistoricoUrl = (id: number,
    params?: AgendamentoControllerListarHistoricoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/agendamentos/${id}/historico-status?${stringifiedParams}` : `${apiBaseUrl}/agendamentos/${id}/historico-status`
}

export const agendamentoControllerListarHistorico = async (id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerListarHistoricoResponse> => {

  return httpClient<agendamentoControllerListarHistoricoResponse>(getAgendamentoControllerListarHistoricoUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAgendamentoControllerListarHistoricoQueryKey = (id: number,
    params?: AgendamentoControllerListarHistoricoParams,) => {
    return [
    `${apiBaseUrl}/agendamentos/${id}/historico-status`, ...(params ? [params] : [])
    ] as const;
    }


export const getAgendamentoControllerListarHistoricoQueryOptions = <TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = unknown>(id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAgendamentoControllerListarHistoricoQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>> = ({ signal }) => agendamentoControllerListarHistorico(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoControllerListarHistoricoQueryResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>>
export type AgendamentoControllerListarHistoricoQueryError = unknown


export function useAgendamentoControllerListarHistorico<TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = unknown>(
 id: number,
    params: undefined |  AgendamentoControllerListarHistoricoParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerListarHistorico<TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = unknown>(
 id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerListarHistorico<TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = unknown>(
 id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAgendamentoControllerListarHistorico<TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = unknown>(
 id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAgendamentoControllerListarHistoricoQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type agendamentoControllerCriarHistoricoResponse201 = {
  data: AgendamentoControllerCriarHistorico201
  status: 201
}

export type agendamentoControllerCriarHistoricoResponseSuccess = (agendamentoControllerCriarHistoricoResponse201) & {
  headers: Headers;
};
;

export type agendamentoControllerCriarHistoricoResponse = (agendamentoControllerCriarHistoricoResponseSuccess)

export const getAgendamentoControllerCriarHistoricoUrl = (id: number,) => {




  return `${apiBaseUrl}/agendamentos/${id}/historico-status`
}

export const agendamentoControllerCriarHistorico = async (id: number,
    criarHistoricoStatusDto: CriarHistoricoStatusDto, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerCriarHistoricoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<agendamentoControllerCriarHistoricoResponse>(getAgendamentoControllerCriarHistoricoUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarHistoricoStatusDto)
  }
);}





export const getAgendamentoControllerCriarHistoricoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>, TError,AgendamentoControllerCriarHistoricoMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>, TError,AgendamentoControllerCriarHistoricoMutationVariables, TContext> => {

const mutationKey = ['agendamentoControllerCriarHistorico'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>, AgendamentoControllerCriarHistoricoMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  agendamentoControllerCriarHistorico(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AgendamentoControllerCriarHistoricoMutationResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>>
    export type AgendamentoControllerCriarHistoricoMutationBody = CriarHistoricoStatusDto
    export type AgendamentoControllerCriarHistoricoMutationError = unknown
    export type AgendamentoControllerCriarHistoricoMutationVariables = {id: number;data: CriarHistoricoStatusDto}

    export const useAgendamentoControllerCriarHistorico = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>, TError,AgendamentoControllerCriarHistoricoMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>,
        TError,
        AgendamentoControllerCriarHistoricoMutationVariables,
        TContext
      > => {
      return useMutation(getAgendamentoControllerCriarHistoricoMutationOptions(options), queryClient);
    }
    export type agendamentoControllerBuscarResponse200 = {
  data: AgendamentoControllerBuscar200
  status: 200
}

export type agendamentoControllerBuscarResponseSuccess = (agendamentoControllerBuscarResponse200) & {
  headers: Headers;
};
;

export type agendamentoControllerBuscarResponse = (agendamentoControllerBuscarResponseSuccess)

export const getAgendamentoControllerBuscarUrl = (id: number,) => {




  return `${apiBaseUrl}/agendamentos/${id}`
}

export const agendamentoControllerBuscar = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerBuscarResponse> => {

  return httpClient<agendamentoControllerBuscarResponse>(getAgendamentoControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAgendamentoControllerBuscarQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/agendamentos/${id}`
    ] as const;
    }


export const getAgendamentoControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAgendamentoControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof agendamentoControllerBuscar>>> = ({ signal }) => agendamentoControllerBuscar(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerBuscar>>>
export type AgendamentoControllerBuscarQueryError = unknown


export function useAgendamentoControllerBuscar<TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerBuscar<TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerBuscar<TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAgendamentoControllerBuscar<TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAgendamentoControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type agendamentoControllerAtualizarResponse200 = {
  data: AgendamentoControllerAtualizar200
  status: 200
}

export type agendamentoControllerAtualizarResponseSuccess = (agendamentoControllerAtualizarResponse200) & {
  headers: Headers;
};
;

export type agendamentoControllerAtualizarResponse = (agendamentoControllerAtualizarResponseSuccess)

export const getAgendamentoControllerAtualizarUrl = (id: number,) => {




  return `${apiBaseUrl}/agendamentos/${id}`
}

export const agendamentoControllerAtualizar = async (id: number,
    atualizarAgendamentoDto: AtualizarAgendamentoDto, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<agendamentoControllerAtualizarResponse>(getAgendamentoControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarAgendamentoDto)
  }
);}





export const getAgendamentoControllerAtualizarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>, TError,AgendamentoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>, TError,AgendamentoControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['agendamentoControllerAtualizar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>, AgendamentoControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  agendamentoControllerAtualizar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AgendamentoControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>>
    export type AgendamentoControllerAtualizarMutationBody = AtualizarAgendamentoDto
    export type AgendamentoControllerAtualizarMutationError = unknown
    export type AgendamentoControllerAtualizarMutationVariables = {id: number;data: AtualizarAgendamentoDto}

    export const useAgendamentoControllerAtualizar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>, TError,AgendamentoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof agendamentoControllerAtualizar>>,
        TError,
        AgendamentoControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getAgendamentoControllerAtualizarMutationOptions(options), queryClient);
    }
    export type agendamentoControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type agendamentoControllerRemoverResponseSuccess = (agendamentoControllerRemoverResponse200) & {
  headers: Headers;
};
;

export type agendamentoControllerRemoverResponse = (agendamentoControllerRemoverResponseSuccess)

export const getAgendamentoControllerRemoverUrl = (id: number,) => {




  return `${apiBaseUrl}/agendamentos/${id}`
}

export const agendamentoControllerRemover = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerRemoverResponse> => {

  return httpClient<agendamentoControllerRemoverResponse>(getAgendamentoControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getAgendamentoControllerRemoverMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerRemover>>, TError,AgendamentoControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerRemover>>, TError,AgendamentoControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['agendamentoControllerRemover'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof agendamentoControllerRemover>>, AgendamentoControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  agendamentoControllerRemover(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AgendamentoControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerRemover>>>

    export type AgendamentoControllerRemoverMutationError = unknown
    export type AgendamentoControllerRemoverMutationVariables = {id: number}

    export const useAgendamentoControllerRemover = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerRemover>>, TError,AgendamentoControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof agendamentoControllerRemover>>,
        TError,
        AgendamentoControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getAgendamentoControllerRemoverMutationOptions(options), queryClient);
    }
