/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AgendamentoBarbeiroRespostaDto,
  AgendamentoControllerCriarHistorico201,
  AgendamentoControllerHorariosAdministradorParams,
  AgendamentoControllerHorariosParams,
  AgendamentoControllerListarHistoricoParams,
  AgendamentoControllerListarParams,
  AgendamentoRespostaDto,
  AtualizarAgendamentoDto,
  CriarAgendamentoDto,
  CriarHistoricoStatusDto,
  ErroRespostaDto,
  HistoricoAgendamentoRespostaDto,
  HorariosDisponiveisRespostaDto,
  LimiteRequisicoesRespostaDto,
  ListaAgendamentosBarbeiroRespostaDto,
  ListaAgendamentosRespostaDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type agendamentoControllerCriarResponse201 = {
  data: AgendamentoRespostaDto
  status: 201
}

export type agendamentoControllerCriarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type agendamentoControllerCriarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type agendamentoControllerCriarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type agendamentoControllerCriarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type agendamentoControllerCriarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type agendamentoControllerCriarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type agendamentoControllerCriarResponseSuccess = (agendamentoControllerCriarResponse201) & {
  headers: Headers;
};
export type agendamentoControllerCriarResponseError = (agendamentoControllerCriarResponse400 | agendamentoControllerCriarResponse401 | agendamentoControllerCriarResponse403 | agendamentoControllerCriarResponse404 | agendamentoControllerCriarResponse409 | agendamentoControllerCriarResponse429) & {
  headers: Headers;
};

export type agendamentoControllerCriarResponse = (agendamentoControllerCriarResponseSuccess | agendamentoControllerCriarResponseError)

export const getAgendamentoControllerCriarUrl = () => {




  return `${apiBaseUrl}/agendamentos`
}

export const agendamentoControllerCriar = async (criarAgendamentoDto: CriarAgendamentoDto, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<agendamentoControllerCriarResponse>(getAgendamentoControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarAgendamentoDto)
  }
);}





export const getAgendamentoControllerCriarMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriar>>, TError,AgendamentoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriar>>, TError,AgendamentoControllerCriarMutationVariables, TContext> => {

const mutationKey = ['agendamentoControllerCriar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof agendamentoControllerCriar>>, AgendamentoControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  agendamentoControllerCriar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AgendamentoControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerCriar>>>
    export type AgendamentoControllerCriarMutationBody = CriarAgendamentoDto
    export type AgendamentoControllerCriarMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type AgendamentoControllerCriarMutationVariables = {data: CriarAgendamentoDto}

    export const useAgendamentoControllerCriar = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriar>>, TError,AgendamentoControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof agendamentoControllerCriar>>,
        TError,
        AgendamentoControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getAgendamentoControllerCriarMutationOptions(options), queryClient);
    }
    export type agendamentoControllerListarResponse200 = {
  data: ListaAgendamentosRespostaDto | ListaAgendamentosBarbeiroRespostaDto
  status: 200
}

export type agendamentoControllerListarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type agendamentoControllerListarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type agendamentoControllerListarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type agendamentoControllerListarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type agendamentoControllerListarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type agendamentoControllerListarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type agendamentoControllerListarResponseSuccess = (agendamentoControllerListarResponse200) & {
  headers: Headers;
};
export type agendamentoControllerListarResponseError = (agendamentoControllerListarResponse400 | agendamentoControllerListarResponse401 | agendamentoControllerListarResponse403 | agendamentoControllerListarResponse404 | agendamentoControllerListarResponse409 | agendamentoControllerListarResponse429) & {
  headers: Headers;
};

export type agendamentoControllerListarResponse = (agendamentoControllerListarResponseSuccess | agendamentoControllerListarResponseError)

export const getAgendamentoControllerListarUrl = (params?: AgendamentoControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/agendamentos?${stringifiedParams}` : `${apiBaseUrl}/agendamentos`
}

export const agendamentoControllerListar = async (params?: AgendamentoControllerListarParams, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerListarResponse> => {

  return httpClient<agendamentoControllerListarResponse>(getAgendamentoControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAgendamentoControllerListarQueryKey = (params?: AgendamentoControllerListarParams,) => {
    return [
    `${apiBaseUrl}/agendamentos`, ...(params ? [params] : [])
    ] as const;
    }


export const getAgendamentoControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(params?: AgendamentoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAgendamentoControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof agendamentoControllerListar>>> = ({ signal }) => agendamentoControllerListar(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerListar>>>
export type AgendamentoControllerListarQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useAgendamentoControllerListar<TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: undefined |  AgendamentoControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerListar<TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: AgendamentoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerListar>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerListar<TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: AgendamentoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAgendamentoControllerListar<TData = Awaited<ReturnType<typeof agendamentoControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: AgendamentoControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAgendamentoControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type agendamentoControllerHorariosResponse200 = {
  data: HorariosDisponiveisRespostaDto
  status: 200
}

export type agendamentoControllerHorariosResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type agendamentoControllerHorariosResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type agendamentoControllerHorariosResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type agendamentoControllerHorariosResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type agendamentoControllerHorariosResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type agendamentoControllerHorariosResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type agendamentoControllerHorariosResponseSuccess = (agendamentoControllerHorariosResponse200) & {
  headers: Headers;
};
export type agendamentoControllerHorariosResponseError = (agendamentoControllerHorariosResponse400 | agendamentoControllerHorariosResponse401 | agendamentoControllerHorariosResponse403 | agendamentoControllerHorariosResponse404 | agendamentoControllerHorariosResponse409 | agendamentoControllerHorariosResponse429) & {
  headers: Headers;
};

export type agendamentoControllerHorariosResponse = (agendamentoControllerHorariosResponseSuccess | agendamentoControllerHorariosResponseError)

export const getAgendamentoControllerHorariosUrl = (params: AgendamentoControllerHorariosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["servicoIds"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/agendamentos/horarios-disponiveis?${stringifiedParams}` : `${apiBaseUrl}/agendamentos/horarios-disponiveis`
}

/**
 * @summary Consulta pública de horários livres
 */
export const agendamentoControllerHorarios = async (params: AgendamentoControllerHorariosParams, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerHorariosResponse> => {

  return httpClient<agendamentoControllerHorariosResponse>(getAgendamentoControllerHorariosUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAgendamentoControllerHorariosQueryKey = (params?: AgendamentoControllerHorariosParams,) => {
    return [
    `${apiBaseUrl}/agendamentos/horarios-disponiveis`, ...(params ? [params] : [])
    ] as const;
    }


export const getAgendamentoControllerHorariosQueryOptions = <TData = Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(params: AgendamentoControllerHorariosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAgendamentoControllerHorariosQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof agendamentoControllerHorarios>>> = ({ signal }) => agendamentoControllerHorarios(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoControllerHorariosQueryResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerHorarios>>>
export type AgendamentoControllerHorariosQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useAgendamentoControllerHorarios<TData = Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: AgendamentoControllerHorariosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerHorarios>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerHorarios>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerHorarios<TData = Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: AgendamentoControllerHorariosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerHorarios>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerHorarios>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerHorarios<TData = Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: AgendamentoControllerHorariosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Consulta pública de horários livres
 */

export function useAgendamentoControllerHorarios<TData = Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: AgendamentoControllerHorariosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorarios>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAgendamentoControllerHorariosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type agendamentoControllerHorariosAdministradorResponse200 = {
  data: HorariosDisponiveisRespostaDto
  status: 200
}

export type agendamentoControllerHorariosAdministradorResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type agendamentoControllerHorariosAdministradorResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type agendamentoControllerHorariosAdministradorResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type agendamentoControllerHorariosAdministradorResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type agendamentoControllerHorariosAdministradorResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type agendamentoControllerHorariosAdministradorResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type agendamentoControllerHorariosAdministradorResponseSuccess = (agendamentoControllerHorariosAdministradorResponse200) & {
  headers: Headers;
};
export type agendamentoControllerHorariosAdministradorResponseError = (agendamentoControllerHorariosAdministradorResponse400 | agendamentoControllerHorariosAdministradorResponse401 | agendamentoControllerHorariosAdministradorResponse403 | agendamentoControllerHorariosAdministradorResponse404 | agendamentoControllerHorariosAdministradorResponse409 | agendamentoControllerHorariosAdministradorResponse429) & {
  headers: Headers;
};

export type agendamentoControllerHorariosAdministradorResponse = (agendamentoControllerHorariosAdministradorResponseSuccess | agendamentoControllerHorariosAdministradorResponseError)

export const getAgendamentoControllerHorariosAdministradorUrl = (params: AgendamentoControllerHorariosAdministradorParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/agendamentos/horarios-disponiveis-administrador?${stringifiedParams}` : `${apiBaseUrl}/agendamentos/horarios-disponiveis-administrador`
}

/**
 * @summary Disponibilidade administrativa com quantidade e desconto
 */
export const agendamentoControllerHorariosAdministrador = async (params: AgendamentoControllerHorariosAdministradorParams, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerHorariosAdministradorResponse> => {

  return httpClient<agendamentoControllerHorariosAdministradorResponse>(getAgendamentoControllerHorariosAdministradorUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAgendamentoControllerHorariosAdministradorQueryKey = (params?: AgendamentoControllerHorariosAdministradorParams,) => {
    return [
    `${apiBaseUrl}/agendamentos/horarios-disponiveis-administrador`, ...(params ? [params] : [])
    ] as const;
    }


export const getAgendamentoControllerHorariosAdministradorQueryOptions = <TData = Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(params: AgendamentoControllerHorariosAdministradorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAgendamentoControllerHorariosAdministradorQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>> = ({ signal }) => agendamentoControllerHorariosAdministrador(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoControllerHorariosAdministradorQueryResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>>
export type AgendamentoControllerHorariosAdministradorQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useAgendamentoControllerHorariosAdministrador<TData = Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: AgendamentoControllerHorariosAdministradorParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerHorariosAdministrador<TData = Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: AgendamentoControllerHorariosAdministradorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerHorariosAdministrador<TData = Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: AgendamentoControllerHorariosAdministradorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Disponibilidade administrativa com quantidade e desconto
 */

export function useAgendamentoControllerHorariosAdministrador<TData = Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: AgendamentoControllerHorariosAdministradorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerHorariosAdministrador>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAgendamentoControllerHorariosAdministradorQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type agendamentoControllerListarHistoricoResponse200 = {
  data: HistoricoAgendamentoRespostaDto
  status: 200
}

export type agendamentoControllerListarHistoricoResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type agendamentoControllerListarHistoricoResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type agendamentoControllerListarHistoricoResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type agendamentoControllerListarHistoricoResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type agendamentoControllerListarHistoricoResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type agendamentoControllerListarHistoricoResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type agendamentoControllerListarHistoricoResponseSuccess = (agendamentoControllerListarHistoricoResponse200) & {
  headers: Headers;
};
export type agendamentoControllerListarHistoricoResponseError = (agendamentoControllerListarHistoricoResponse400 | agendamentoControllerListarHistoricoResponse401 | agendamentoControllerListarHistoricoResponse403 | agendamentoControllerListarHistoricoResponse404 | agendamentoControllerListarHistoricoResponse409 | agendamentoControllerListarHistoricoResponse429) & {
  headers: Headers;
};

export type agendamentoControllerListarHistoricoResponse = (agendamentoControllerListarHistoricoResponseSuccess | agendamentoControllerListarHistoricoResponseError)

export const getAgendamentoControllerListarHistoricoUrl = (id: number,
    params?: AgendamentoControllerListarHistoricoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/agendamentos/${id}/historico-status?${stringifiedParams}` : `${apiBaseUrl}/agendamentos/${id}/historico-status`
}

export const agendamentoControllerListarHistorico = async (id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerListarHistoricoResponse> => {

  return httpClient<agendamentoControllerListarHistoricoResponse>(getAgendamentoControllerListarHistoricoUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAgendamentoControllerListarHistoricoQueryKey = (id: number,
    params?: AgendamentoControllerListarHistoricoParams,) => {
    return [
    `${apiBaseUrl}/agendamentos/${id}/historico-status`, ...(params ? [params] : [])
    ] as const;
    }


export const getAgendamentoControllerListarHistoricoQueryOptions = <TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAgendamentoControllerListarHistoricoQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>> = ({ signal }) => agendamentoControllerListarHistorico(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoControllerListarHistoricoQueryResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>>
export type AgendamentoControllerListarHistoricoQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useAgendamentoControllerListarHistorico<TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number,
    params: undefined |  AgendamentoControllerListarHistoricoParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerListarHistorico<TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerListarHistorico<TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAgendamentoControllerListarHistorico<TData = Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number,
    params?: AgendamentoControllerListarHistoricoParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerListarHistorico>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAgendamentoControllerListarHistoricoQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type agendamentoControllerCriarHistoricoResponse201 = {
  data: AgendamentoControllerCriarHistorico201
  status: 201
}

export type agendamentoControllerCriarHistoricoResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type agendamentoControllerCriarHistoricoResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type agendamentoControllerCriarHistoricoResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type agendamentoControllerCriarHistoricoResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type agendamentoControllerCriarHistoricoResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type agendamentoControllerCriarHistoricoResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type agendamentoControllerCriarHistoricoResponseSuccess = (agendamentoControllerCriarHistoricoResponse201) & {
  headers: Headers;
};
export type agendamentoControllerCriarHistoricoResponseError = (agendamentoControllerCriarHistoricoResponse400 | agendamentoControllerCriarHistoricoResponse401 | agendamentoControllerCriarHistoricoResponse403 | agendamentoControllerCriarHistoricoResponse404 | agendamentoControllerCriarHistoricoResponse409 | agendamentoControllerCriarHistoricoResponse429) & {
  headers: Headers;
};

export type agendamentoControllerCriarHistoricoResponse = (agendamentoControllerCriarHistoricoResponseSuccess | agendamentoControllerCriarHistoricoResponseError)

export const getAgendamentoControllerCriarHistoricoUrl = (id: number,) => {




  return `${apiBaseUrl}/agendamentos/${id}/historico-status`
}

export const agendamentoControllerCriarHistorico = async (id: number,
    criarHistoricoStatusDto: CriarHistoricoStatusDto, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerCriarHistoricoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<agendamentoControllerCriarHistoricoResponse>(getAgendamentoControllerCriarHistoricoUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarHistoricoStatusDto)
  }
);}





export const getAgendamentoControllerCriarHistoricoMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>, TError,AgendamentoControllerCriarHistoricoMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>, TError,AgendamentoControllerCriarHistoricoMutationVariables, TContext> => {

const mutationKey = ['agendamentoControllerCriarHistorico'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>, AgendamentoControllerCriarHistoricoMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  agendamentoControllerCriarHistorico(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AgendamentoControllerCriarHistoricoMutationResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>>
    export type AgendamentoControllerCriarHistoricoMutationBody = CriarHistoricoStatusDto
    export type AgendamentoControllerCriarHistoricoMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type AgendamentoControllerCriarHistoricoMutationVariables = {id: number;data: CriarHistoricoStatusDto}

    export const useAgendamentoControllerCriarHistorico = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>, TError,AgendamentoControllerCriarHistoricoMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof agendamentoControllerCriarHistorico>>,
        TError,
        AgendamentoControllerCriarHistoricoMutationVariables,
        TContext
      > => {
      return useMutation(getAgendamentoControllerCriarHistoricoMutationOptions(options), queryClient);
    }
    export type agendamentoControllerBuscarResponse200 = {
  data: AgendamentoRespostaDto | AgendamentoBarbeiroRespostaDto
  status: 200
}

export type agendamentoControllerBuscarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type agendamentoControllerBuscarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type agendamentoControllerBuscarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type agendamentoControllerBuscarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type agendamentoControllerBuscarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type agendamentoControllerBuscarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type agendamentoControllerBuscarResponseSuccess = (agendamentoControllerBuscarResponse200) & {
  headers: Headers;
};
export type agendamentoControllerBuscarResponseError = (agendamentoControllerBuscarResponse400 | agendamentoControllerBuscarResponse401 | agendamentoControllerBuscarResponse403 | agendamentoControllerBuscarResponse404 | agendamentoControllerBuscarResponse409 | agendamentoControllerBuscarResponse429) & {
  headers: Headers;
};

export type agendamentoControllerBuscarResponse = (agendamentoControllerBuscarResponseSuccess | agendamentoControllerBuscarResponseError)

export const getAgendamentoControllerBuscarUrl = (id: number,) => {




  return `${apiBaseUrl}/agendamentos/${id}`
}

export const agendamentoControllerBuscar = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerBuscarResponse> => {

  return httpClient<agendamentoControllerBuscarResponse>(getAgendamentoControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAgendamentoControllerBuscarQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/agendamentos/${id}`
    ] as const;
    }


export const getAgendamentoControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAgendamentoControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof agendamentoControllerBuscar>>> = ({ signal }) => agendamentoControllerBuscar(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AgendamentoControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerBuscar>>>
export type AgendamentoControllerBuscarQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useAgendamentoControllerBuscar<TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerBuscar<TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof agendamentoControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof agendamentoControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAgendamentoControllerBuscar<TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAgendamentoControllerBuscar<TData = Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof agendamentoControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAgendamentoControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type agendamentoControllerAtualizarResponse200 = {
  data: AgendamentoRespostaDto | AgendamentoBarbeiroRespostaDto
  status: 200
}

export type agendamentoControllerAtualizarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type agendamentoControllerAtualizarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type agendamentoControllerAtualizarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type agendamentoControllerAtualizarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type agendamentoControllerAtualizarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type agendamentoControllerAtualizarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type agendamentoControllerAtualizarResponseSuccess = (agendamentoControllerAtualizarResponse200) & {
  headers: Headers;
};
export type agendamentoControllerAtualizarResponseError = (agendamentoControllerAtualizarResponse400 | agendamentoControllerAtualizarResponse401 | agendamentoControllerAtualizarResponse403 | agendamentoControllerAtualizarResponse404 | agendamentoControllerAtualizarResponse409 | agendamentoControllerAtualizarResponse429) & {
  headers: Headers;
};

export type agendamentoControllerAtualizarResponse = (agendamentoControllerAtualizarResponseSuccess | agendamentoControllerAtualizarResponseError)

export const getAgendamentoControllerAtualizarUrl = (id: number,) => {




  return `${apiBaseUrl}/agendamentos/${id}`
}

export const agendamentoControllerAtualizar = async (id: number,
    atualizarAgendamentoDto: AtualizarAgendamentoDto, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<agendamentoControllerAtualizarResponse>(getAgendamentoControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarAgendamentoDto)
  }
);}





export const getAgendamentoControllerAtualizarMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>, TError,AgendamentoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>, TError,AgendamentoControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['agendamentoControllerAtualizar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>, AgendamentoControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  agendamentoControllerAtualizar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AgendamentoControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>>
    export type AgendamentoControllerAtualizarMutationBody = AtualizarAgendamentoDto
    export type AgendamentoControllerAtualizarMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type AgendamentoControllerAtualizarMutationVariables = {id: number;data: AtualizarAgendamentoDto}

    export const useAgendamentoControllerAtualizar = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerAtualizar>>, TError,AgendamentoControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof agendamentoControllerAtualizar>>,
        TError,
        AgendamentoControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getAgendamentoControllerAtualizarMutationOptions(options), queryClient);
    }
    export type agendamentoControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type agendamentoControllerRemoverResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type agendamentoControllerRemoverResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type agendamentoControllerRemoverResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type agendamentoControllerRemoverResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type agendamentoControllerRemoverResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type agendamentoControllerRemoverResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type agendamentoControllerRemoverResponseSuccess = (agendamentoControllerRemoverResponse200) & {
  headers: Headers;
};
export type agendamentoControllerRemoverResponseError = (agendamentoControllerRemoverResponse400 | agendamentoControllerRemoverResponse401 | agendamentoControllerRemoverResponse403 | agendamentoControllerRemoverResponse404 | agendamentoControllerRemoverResponse409 | agendamentoControllerRemoverResponse429) & {
  headers: Headers;
};

export type agendamentoControllerRemoverResponse = (agendamentoControllerRemoverResponseSuccess | agendamentoControllerRemoverResponseError)

export const getAgendamentoControllerRemoverUrl = (id: number,) => {




  return `${apiBaseUrl}/agendamentos/${id}`
}

export const agendamentoControllerRemover = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<agendamentoControllerRemoverResponse> => {

  return httpClient<agendamentoControllerRemoverResponse>(getAgendamentoControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getAgendamentoControllerRemoverMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerRemover>>, TError,AgendamentoControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerRemover>>, TError,AgendamentoControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['agendamentoControllerRemover'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof agendamentoControllerRemover>>, AgendamentoControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  agendamentoControllerRemover(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AgendamentoControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof agendamentoControllerRemover>>>

    export type AgendamentoControllerRemoverMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type AgendamentoControllerRemoverMutationVariables = {id: number}

    export const useAgendamentoControllerRemover = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof agendamentoControllerRemover>>, TError,AgendamentoControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof agendamentoControllerRemover>>,
        TError,
        AgendamentoControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getAgendamentoControllerRemoverMutationOptions(options), queryClient);
    }
