/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type AgendamentoControllerHorariosParams = {
/**
 * @minimum 1
 */
idFilial: number;
/**
 * @minimum 1
 */
idBarbeiro: number;
/**
 * @pattern ^\d{4}-\d{2}-\d{2}$
 */
data: string;
/**
 * @minItems 1
 * @items.minimum 1
 */
servicoIds: number[];
};
