/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { AgendamentoControllerListarStatus } from './agendamentoControllerListarStatus';

export type AgendamentoControllerListarParams = {
/**
 * Número da página a ser retornada.
 * @minimum 1
 */
pagina?: number;
/**
 * Quantidade de registros por página.
 * @minimum 1
 * @maximum 100
 */
limite?: number;
idCliente?: number;
idBarbeiro?: number;
idFilial?: number;
status?: AgendamentoControllerListarStatus;
inicioDe?: string;
inicioAte?: string;
};
