/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type AgendamentoDashboardControllerObterParams = {
/**
 * Primeiro dia do período.
 */
inicioDe?: string;
/**
 * Último dia do período, inclusive.
 */
inicioAte?: string;
};
