/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { AgendaDashboardRespostaDtoPeriodo } from './agendaDashboardRespostaDtoPeriodo';
import type { AgendaDashboardRespostaDtoTotaisPorStatus } from './agendaDashboardRespostaDtoTotaisPorStatus';
import type { DiaAgendaDashboardDto } from './diaAgendaDashboardDto';

export interface AgendaDashboardRespostaDto {
  geradoEm: string;
  periodo: AgendaDashboardRespostaDtoPeriodo;
  totaisPorStatus: AgendaDashboardRespostaDtoTotaisPorStatus;
  dias: DiaAgendaDashboardDto[];
}
