/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export interface AtualizarServicoDto {
  /** @minLength 2 */
  nome?: string;
  descricao?: string;
  /** @minimum 1 */
  preco?: number;
  /** @minimum 1 */
  duracaoMinutos?: number;
}
