/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type AtualizarAdministradorDtoStatus = typeof AtualizarAdministradorDtoStatus[keyof typeof AtualizarAdministradorDtoStatus];


export const AtualizarAdministradorDtoStatus = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
  BLOQUEADO: 'BLOQUEADO',
} as const;
