/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { AtualizarBarbeiroDtoStatus } from './atualizarBarbeiroDtoStatus';

export interface AtualizarBarbeiroDto {
  /** @minLength 2 */
  nome?: string;
  email?: string;
  /** @minLength 8 */
  senha?: string;
  idFilial?: number;
  descricao?: string;
  dataAdmissao?: string;
  status?: AtualizarBarbeiroDtoStatus;
}
