/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { AtualizarEnderecoDto } from './atualizarEnderecoDto';
import type { AtualizarFilialDtoStatus } from './atualizarFilialDtoStatus';

export interface AtualizarFilialDto {
  nome?: string;
  cnpj?: string;
  telefone?: string;
  email?: string;
  status?: AtualizarFilialDtoStatus;
  endereco?: AtualizarEnderecoDto;
}
