/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { AtualizarAgendamentoDtoStatus } from './atualizarAgendamentoDtoStatus';
import type { ItemAgendamentoDto } from './itemAgendamentoDto';

export interface AtualizarAgendamentoDto {
  inicio?: string;
  /** @minItems 1 */
  servicos?: ItemAgendamentoDto[];
  /** @minItems 1 */
  servicoIds?: number[];
  observacaoCliente?: string;
  observacaoInterna?: string;
  status?: AtualizarAgendamentoDtoStatus;
  motivoCancelamento?: string;
}
