/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { AtualizarAdministradorDtoStatus } from './atualizarAdministradorDtoStatus';

export interface AtualizarAdministradorDto {
  /** @minLength 2 */
  nome?: string;
  email?: string;
  /**
     * @minLength 15
     * @maxLength 128
     */
  senha?: string;
  telefone?: string;
  status?: AtualizarAdministradorDtoStatus;
  dataInicioAdministracao?: string;
  observacao?: string;
}
