/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type BarbeiroDashboardControllerObterStatus = typeof BarbeiroDashboardControllerObterStatus[keyof typeof BarbeiroDashboardControllerObterStatus];


export const BarbeiroDashboardControllerObterStatus = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
  AFASTADO: 'AFASTADO',
} as const;
