/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { BarbeiroDashboardDtoStatus } from './barbeiroDashboardDtoStatus';

export interface BarbeiroDashboardDto {
  id: number;
  nome: string;
  /** @nullable */
  fotoUrl: string | null;
  filial: string;
  status: BarbeiroDashboardDtoStatus;
  atendimentosHoje: number;
  receitaMes: number;
  comissoesRegistradasMes: number;
  comissoesAPagar: number;
}
