/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { BarbeiroRespostaDtoStatusProfissional } from './barbeiroRespostaDtoStatusProfissional';
import type { FilialResumoRespostaDto } from './filialResumoRespostaDto';
import type { UsuarioPublicoRespostaDto } from './usuarioPublicoRespostaDto';

export interface BarbeiroRespostaDto {
  id: number;
  idFilial: number;
  nomeProfissional: string;
  /** @nullable */
  descricao?: string | null;
  /** @nullable */
  fotoUrl?: string | null;
  /** @nullable */
  dataAdmissao?: string | null;
  statusProfissional: BarbeiroRespostaDtoStatusProfissional;
  usuario: UsuarioPublicoRespostaDto;
  filial: FilialResumoRespostaDto;
}
