/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { BarbeiroDashboardDto } from './barbeiroDashboardDto';
import type { BarbeirosDashboardRespostaDtoIndicadores } from './barbeirosDashboardRespostaDtoIndicadores';
import type { MetaPaginacaoDto } from './metaPaginacaoDto';

export interface BarbeirosDashboardRespostaDto {
  geradoEm: string;
  indicadores: BarbeirosDashboardRespostaDtoIndicadores;
  data: BarbeiroDashboardDto[];
  meta: MetaPaginacaoDto;
}
