/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { Object } from './object';

export type BarbeiroControllerListarParams = {
/**
 * @minimum 1
 */
pagina?: Object;
/**
 * @minimum 1
 * @maximum 100
 */
limite?: Object;
};
