/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { ClienteDashboardDto } from './clienteDashboardDto';
import type { ClientesDashboardRespostaDtoIndicadores } from './clientesDashboardRespostaDtoIndicadores';
import type { MetaPaginacaoDto } from './metaPaginacaoDto';

export interface ClientesDashboardRespostaDto {
  geradoEm: string;
  indicadores: ClientesDashboardRespostaDtoIndicadores;
  data: ClienteDashboardDto[];
  meta: MetaPaginacaoDto;
}
