/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type ClienteDashboardControllerObterStatus = typeof ClienteDashboardControllerObterStatus[keyof typeof ClienteDashboardControllerObterStatus];


export const ClienteDashboardControllerObterStatus = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
  BLOQUEADO: 'BLOQUEADO',
} as const;
