/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type ClienteDashboardDtoStatus = typeof ClienteDashboardDtoStatus[keyof typeof ClienteDashboardDtoStatus];


export const ClienteDashboardDtoStatus = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
  BLOQUEADO: 'BLOQUEADO',
} as const;
