/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type ComissaoControllerListarStatus = typeof ComissaoControllerListarStatus[keyof typeof ComissaoControllerListarStatus];


export const ComissaoControllerListarStatus = {
  PREVISTA: 'PREVISTA',
  LIBERADA: 'LIBERADA',
  PAGA: 'PAGA',
  CANCELADA: 'CANCELADA',
  ESTORNADA: 'ESTORNADA',
} as const;
