/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type CriarBarbeiroDtoStatusProfissional = typeof CriarBarbeiroDtoStatusProfissional[keyof typeof CriarBarbeiroDtoStatusProfissional];


export const CriarBarbeiroDtoStatusProfissional = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
  AFASTADO: 'AFASTADO',
} as const;
