/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type CriarUsuarioDtoTipoPerfil = typeof CriarUsuarioDtoTipoPerfil[keyof typeof CriarUsuarioDtoTipoPerfil];


export const CriarUsuarioDtoTipoPerfil = {
  CLIENTE: 'CLIENTE',
  BARBEIRO: 'BARBEIRO',
  ADMIN: 'ADMIN',
} as const;
