/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { CriarAgendamentoDtoOrigem } from './criarAgendamentoDtoOrigem';
import type { ItemAgendamentoDto } from './itemAgendamentoDto';

export interface CriarAgendamentoDto {
  idCliente: number;
  idBarbeiro: number;
  idFilial: number;
  inicio: string;
  /** @minItems 1 */
  servicos?: ItemAgendamentoDto[];
  /** @minItems 1 */
  servicoIds?: number[];
  origem?: CriarAgendamentoDtoOrigem;
  observacaoCliente?: string;
  observacaoInterna?: string;
}
