/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { CriarBarbeiroDtoStatusProfissional } from './criarBarbeiroDtoStatusProfissional';

export interface CriarBarbeiroDto {
  /** @minLength 2 */
  nome: string;
  email: string;
  /**
     * @minLength 15
     * @maxLength 128
     */
  senha: string;
  idFilial: number;
  nomeProfissional?: string;
  descricao?: string;
  fotoUrl?: string;
  dataAdmissao?: string;
  statusProfissional?: CriarBarbeiroDtoStatusProfissional;
}
