/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type CriarAgendamentoDtoOrigem = typeof CriarAgendamentoDtoOrigem[keyof typeof CriarAgendamentoDtoOrigem];


export const CriarAgendamentoDtoOrigem = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  BARBEIRO: 'BARBEIRO',
  SITE: 'SITE',
} as const;
