/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export interface CriarComissaoDto {
  idAgendamentoServico: number;
  idBarbeiro: number;
  /** @minimum 1 */
  percentualAplicado: number;
  observacao?: string;
}
