/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { AgendamentoResumoDashboardDto } from './agendamentoResumoDashboardDto';
import type { BarbeiroDesempenhoDashboardDto } from './barbeiroDesempenhoDashboardDto';
import type { IndicadorDashboardDto } from './indicadorDashboardDto';
import type { PontoSerieDashboardDto } from './pontoSerieDashboardDto';
import type { ServicoDashboardDto } from './servicoDashboardDto';

export interface DashboardAdministradorRespostaDto {
  geradoEm: string;
  agendamentosHoje: IndicadorDashboardDto;
  receitaHoje: IndicadorDashboardDto;
  clientesAtivos: number;
  novosClientesNoMes: number;
  barbeirosAtivos: number;
  receitaUltimosSeteDias: PontoSerieDashboardDto[];
  servicosNoMes: ServicoDashboardDto[];
  desempenhoBarbeiros: BarbeiroDesempenhoDashboardDto[];
  agendamentosRecentes: AgendamentoResumoDashboardDto[];
}
