/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { ItemAgendaDashboardDto } from './itemAgendaDashboardDto';

export interface DiaAgendaDashboardDto {
  data: string;
  rotulo: string;
  agendamentos: ItemAgendaDashboardDto[];
}
