/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type FilialResumoRespostaDtoStatus = typeof FilialResumoRespostaDtoStatus[keyof typeof FilialResumoRespostaDtoStatus];


export const FilialResumoRespostaDtoStatus = {
  ATIVA: 'ATIVA',
  INATIVA: 'INATIVA',
  EM_MANUTENCAO: 'EM_MANUTENCAO',
} as const;
