/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { ComissaoBarbeiroDashboardDto } from './comissaoBarbeiroDashboardDto';
import type { FinanceiroDashboardRespostaDtoIndicadores } from './financeiroDashboardRespostaDtoIndicadores';
import type { FinanceiroDashboardRespostaDtoPeriodo } from './financeiroDashboardRespostaDtoPeriodo';
import type { MovimentacaoFinanceiraDashboardDto } from './movimentacaoFinanceiraDashboardDto';
import type { SemanaFinanceiraDashboardDto } from './semanaFinanceiraDashboardDto';

export interface FinanceiroDashboardRespostaDto {
  geradoEm: string;
  periodo: FinanceiroDashboardRespostaDtoPeriodo;
  indicadores: FinanceiroDashboardRespostaDtoIndicadores;
  fluxoSemanal: SemanaFinanceiraDashboardDto[];
  movimentacoesRecentes: MovimentacaoFinanceiraDashboardDto[];
  comissoesPorBarbeiro: ComissaoBarbeiroDashboardDto[];
}
