/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { ItemAgendaDashboardDtoStatus } from './itemAgendaDashboardDtoStatus';

export interface ItemAgendaDashboardDto {
  id: number;
  inicio: string;
  fim: string;
  cliente: string;
  barbeiro: string;
  servicos: string[];
  status: ItemAgendaDashboardDtoStatus;
  total: number;
}
