/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export interface ItemAgendamentoDto {
  idServico: number;
  /** @minimum 1 */
  quantidade: number;
  /** @minimum 0 */
  desconto: number;
}
