/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export interface LimiteRequisicoesRespostaDto {
  statusCode: number;
  message: string | string[];
  error?: string;
  /** Segundos até uma nova tentativa. */
  retryAfter: number;
}
