/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { MetaPaginacaoDto } from './metaPaginacaoDto';
import type { ServicoRespostaDto } from './servicoRespostaDto';

export interface ListaServicosRespostaDto {
  data: ServicoRespostaDto[];
  meta: MetaPaginacaoDto;
}
