/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { AgendamentoRespostaDto } from './agendamentoRespostaDto';
import type { MetaPaginacaoDto } from './metaPaginacaoDto';

export interface ListaAgendamentosRespostaDto {
  data: AgendamentoRespostaDto[];
  meta: MetaPaginacaoDto;
}
