/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { FilialPublicaDto } from './filialPublicaDto';
import type { MetaPaginacaoDto } from './metaPaginacaoDto';

export interface ListaFiliaisPublicasDto {
  data: FilialPublicaDto[];
  meta: MetaPaginacaoDto;
}
