/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { MovimentacaoFinanceiraDashboardDtoCategoria } from './movimentacaoFinanceiraDashboardDtoCategoria';

export interface MovimentacaoFinanceiraDashboardDto {
  id: number;
  data: string;
  descricao: string;
  categoria: MovimentacaoFinanceiraDashboardDtoCategoria;
  valor: number;
  status: string;
}
