/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type MovimentacaoFinanceiraDashboardDtoCategoria = typeof MovimentacaoFinanceiraDashboardDtoCategoria[keyof typeof MovimentacaoFinanceiraDashboardDtoCategoria];


export const MovimentacaoFinanceiraDashboardDtoCategoria = {
  Receita: 'Receita',
} as const;
