/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export interface ServicoAdministrativoDashboardDto {
  id: number;
  nome: string;
  /** @nullable */
  descricao: string | null;
  duracaoMinutos: number;
  preco: number;
  ativo: boolean;
  realizadosMes: number;
  receitaMes: number;
}
