/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { UsuarioRespostaDtoTipoPerfil } from './usuarioRespostaDtoTipoPerfil';

export interface UsuarioRespostaDto {
  id: number;
  nome: string;
  email: string;
  tipoPerfil: UsuarioRespostaDtoTipoPerfil;
  dataCadastro: string;
  createdAt: string;
  updatedAt: string;
}
