/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */

export type UsuarioPublicoRespostaDtoStatus = typeof UsuarioPublicoRespostaDtoStatus[keyof typeof UsuarioPublicoRespostaDtoStatus];


export const UsuarioPublicoRespostaDtoStatus = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
  BLOQUEADO: 'BLOQUEADO',
} as const;
