/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import type { UsuarioPublicoRespostaDtoStatus } from './usuarioPublicoRespostaDtoStatus';

export interface UsuarioPublicoRespostaDto {
  id: number;
  idPapel: number;
  nome: string;
  email: string;
  /** @nullable */
  telefone?: string | null;
  status: UsuarioPublicoRespostaDtoStatus;
  dataCadastro: string;
  dataAtualizacao: string;
  /** @nullable */
  ultimoAcesso?: string | null;
}
