/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AtualizarPapelDto,
  AtualizarPapelPermissaoDto,
  CriarPapelDto,
  ErroRespostaDto,
  LimiteRequisicoesRespostaDto,
  PapelControllerListarParams,
  PapelControllerListarPermissoes200Item,
  VincularPermissaoDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type papelControllerCriarResponse201 = {
  data: void
  status: 201
}

export type papelControllerCriarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type papelControllerCriarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type papelControllerCriarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type papelControllerCriarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type papelControllerCriarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type papelControllerCriarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type papelControllerCriarResponseSuccess = (papelControllerCriarResponse201) & {
  headers: Headers;
};
export type papelControllerCriarResponseError = (papelControllerCriarResponse400 | papelControllerCriarResponse401 | papelControllerCriarResponse403 | papelControllerCriarResponse404 | papelControllerCriarResponse409 | papelControllerCriarResponse429) & {
  headers: Headers;
};

export type papelControllerCriarResponse = (papelControllerCriarResponseSuccess | papelControllerCriarResponseError)

export const getPapelControllerCriarUrl = () => {




  return `${apiBaseUrl}/papeis`
}

export const papelControllerCriar = async (criarPapelDto: CriarPapelDto, options?: Parameters<typeof httpClient>[1]): Promise<papelControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<papelControllerCriarResponse>(getPapelControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarPapelDto)
  }
);}





export const getPapelControllerCriarMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerCriar>>, TError,PapelControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof papelControllerCriar>>, TError,PapelControllerCriarMutationVariables, TContext> => {

const mutationKey = ['papelControllerCriar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof papelControllerCriar>>, PapelControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  papelControllerCriar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PapelControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof papelControllerCriar>>>
    export type PapelControllerCriarMutationBody = CriarPapelDto
    export type PapelControllerCriarMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type PapelControllerCriarMutationVariables = {data: CriarPapelDto}

    export const usePapelControllerCriar = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerCriar>>, TError,PapelControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof papelControllerCriar>>,
        TError,
        PapelControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getPapelControllerCriarMutationOptions(options), queryClient);
    }
    export type papelControllerListarResponse200 = {
  data: void
  status: 200
}

export type papelControllerListarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type papelControllerListarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type papelControllerListarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type papelControllerListarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type papelControllerListarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type papelControllerListarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type papelControllerListarResponseSuccess = (papelControllerListarResponse200) & {
  headers: Headers;
};
export type papelControllerListarResponseError = (papelControllerListarResponse400 | papelControllerListarResponse401 | papelControllerListarResponse403 | papelControllerListarResponse404 | papelControllerListarResponse409 | papelControllerListarResponse429) & {
  headers: Headers;
};

export type papelControllerListarResponse = (papelControllerListarResponseSuccess | papelControllerListarResponseError)

export const getPapelControllerListarUrl = (params?: PapelControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/papeis?${stringifiedParams}` : `${apiBaseUrl}/papeis`
}

export const papelControllerListar = async (params?: PapelControllerListarParams, options?: Parameters<typeof httpClient>[1]): Promise<papelControllerListarResponse> => {

  return httpClient<papelControllerListarResponse>(getPapelControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPapelControllerListarQueryKey = (params?: PapelControllerListarParams,) => {
    return [
    `${apiBaseUrl}/papeis`, ...(params ? [params] : [])
    ] as const;
    }


export const getPapelControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof papelControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(params?: PapelControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPapelControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof papelControllerListar>>> = ({ signal }) => papelControllerListar(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof papelControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PapelControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof papelControllerListar>>>
export type PapelControllerListarQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function usePapelControllerListar<TData = Awaited<ReturnType<typeof papelControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: undefined |  PapelControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof papelControllerListar>>,
          TError,
          Awaited<ReturnType<typeof papelControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePapelControllerListar<TData = Awaited<ReturnType<typeof papelControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: PapelControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof papelControllerListar>>,
          TError,
          Awaited<ReturnType<typeof papelControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePapelControllerListar<TData = Awaited<ReturnType<typeof papelControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: PapelControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePapelControllerListar<TData = Awaited<ReturnType<typeof papelControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: PapelControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPapelControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type papelControllerBuscarResponse200 = {
  data: void
  status: 200
}

export type papelControllerBuscarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type papelControllerBuscarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type papelControllerBuscarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type papelControllerBuscarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type papelControllerBuscarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type papelControllerBuscarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type papelControllerBuscarResponseSuccess = (papelControllerBuscarResponse200) & {
  headers: Headers;
};
export type papelControllerBuscarResponseError = (papelControllerBuscarResponse400 | papelControllerBuscarResponse401 | papelControllerBuscarResponse403 | papelControllerBuscarResponse404 | papelControllerBuscarResponse409 | papelControllerBuscarResponse429) & {
  headers: Headers;
};

export type papelControllerBuscarResponse = (papelControllerBuscarResponseSuccess | papelControllerBuscarResponseError)

export const getPapelControllerBuscarUrl = (id: number,) => {




  return `${apiBaseUrl}/papeis/${id}`
}

export const papelControllerBuscar = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<papelControllerBuscarResponse> => {

  return httpClient<papelControllerBuscarResponse>(getPapelControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPapelControllerBuscarQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/papeis/${id}`
    ] as const;
    }


export const getPapelControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof papelControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPapelControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof papelControllerBuscar>>> = ({ signal }) => papelControllerBuscar(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof papelControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PapelControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof papelControllerBuscar>>>
export type PapelControllerBuscarQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function usePapelControllerBuscar<TData = Awaited<ReturnType<typeof papelControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof papelControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof papelControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePapelControllerBuscar<TData = Awaited<ReturnType<typeof papelControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof papelControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof papelControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePapelControllerBuscar<TData = Awaited<ReturnType<typeof papelControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePapelControllerBuscar<TData = Awaited<ReturnType<typeof papelControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPapelControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type papelControllerAtualizarResponse200 = {
  data: void
  status: 200
}

export type papelControllerAtualizarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type papelControllerAtualizarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type papelControllerAtualizarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type papelControllerAtualizarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type papelControllerAtualizarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type papelControllerAtualizarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type papelControllerAtualizarResponseSuccess = (papelControllerAtualizarResponse200) & {
  headers: Headers;
};
export type papelControllerAtualizarResponseError = (papelControllerAtualizarResponse400 | papelControllerAtualizarResponse401 | papelControllerAtualizarResponse403 | papelControllerAtualizarResponse404 | papelControllerAtualizarResponse409 | papelControllerAtualizarResponse429) & {
  headers: Headers;
};

export type papelControllerAtualizarResponse = (papelControllerAtualizarResponseSuccess | papelControllerAtualizarResponseError)

export const getPapelControllerAtualizarUrl = (id: number,) => {




  return `${apiBaseUrl}/papeis/${id}`
}

export const papelControllerAtualizar = async (id: number,
    atualizarPapelDto: AtualizarPapelDto, options?: Parameters<typeof httpClient>[1]): Promise<papelControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<papelControllerAtualizarResponse>(getPapelControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarPapelDto)
  }
);}





export const getPapelControllerAtualizarMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerAtualizar>>, TError,PapelControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof papelControllerAtualizar>>, TError,PapelControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['papelControllerAtualizar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof papelControllerAtualizar>>, PapelControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  papelControllerAtualizar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PapelControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof papelControllerAtualizar>>>
    export type PapelControllerAtualizarMutationBody = AtualizarPapelDto
    export type PapelControllerAtualizarMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type PapelControllerAtualizarMutationVariables = {id: number;data: AtualizarPapelDto}

    export const usePapelControllerAtualizar = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerAtualizar>>, TError,PapelControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof papelControllerAtualizar>>,
        TError,
        PapelControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getPapelControllerAtualizarMutationOptions(options), queryClient);
    }
    export type papelControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type papelControllerRemoverResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type papelControllerRemoverResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type papelControllerRemoverResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type papelControllerRemoverResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type papelControllerRemoverResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type papelControllerRemoverResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type papelControllerRemoverResponseSuccess = (papelControllerRemoverResponse200) & {
  headers: Headers;
};
export type papelControllerRemoverResponseError = (papelControllerRemoverResponse400 | papelControllerRemoverResponse401 | papelControllerRemoverResponse403 | papelControllerRemoverResponse404 | papelControllerRemoverResponse409 | papelControllerRemoverResponse429) & {
  headers: Headers;
};

export type papelControllerRemoverResponse = (papelControllerRemoverResponseSuccess | papelControllerRemoverResponseError)

export const getPapelControllerRemoverUrl = (id: number,) => {




  return `${apiBaseUrl}/papeis/${id}`
}

export const papelControllerRemover = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<papelControllerRemoverResponse> => {

  return httpClient<papelControllerRemoverResponse>(getPapelControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getPapelControllerRemoverMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerRemover>>, TError,PapelControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof papelControllerRemover>>, TError,PapelControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['papelControllerRemover'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof papelControllerRemover>>, PapelControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  papelControllerRemover(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PapelControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof papelControllerRemover>>>

    export type PapelControllerRemoverMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type PapelControllerRemoverMutationVariables = {id: number}

    export const usePapelControllerRemover = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerRemover>>, TError,PapelControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof papelControllerRemover>>,
        TError,
        PapelControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getPapelControllerRemoverMutationOptions(options), queryClient);
    }
    export type papelControllerListarPermissoesResponse200 = {
  data: PapelControllerListarPermissoes200Item[]
  status: 200
}

export type papelControllerListarPermissoesResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type papelControllerListarPermissoesResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type papelControllerListarPermissoesResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type papelControllerListarPermissoesResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type papelControllerListarPermissoesResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type papelControllerListarPermissoesResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type papelControllerListarPermissoesResponseSuccess = (papelControllerListarPermissoesResponse200) & {
  headers: Headers;
};
export type papelControllerListarPermissoesResponseError = (papelControllerListarPermissoesResponse400 | papelControllerListarPermissoesResponse401 | papelControllerListarPermissoesResponse403 | papelControllerListarPermissoesResponse404 | papelControllerListarPermissoesResponse409 | papelControllerListarPermissoesResponse429) & {
  headers: Headers;
};

export type papelControllerListarPermissoesResponse = (papelControllerListarPermissoesResponseSuccess | papelControllerListarPermissoesResponseError)

export const getPapelControllerListarPermissoesUrl = (id: number,) => {




  return `${apiBaseUrl}/papeis/${id}/permissoes`
}

export const papelControllerListarPermissoes = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<papelControllerListarPermissoesResponse> => {

  return httpClient<papelControllerListarPermissoesResponse>(getPapelControllerListarPermissoesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPapelControllerListarPermissoesQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/papeis/${id}/permissoes`
    ] as const;
    }


export const getPapelControllerListarPermissoesQueryOptions = <TData = Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPapelControllerListarPermissoesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof papelControllerListarPermissoes>>> = ({ signal }) => papelControllerListarPermissoes(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PapelControllerListarPermissoesQueryResult = NonNullable<Awaited<ReturnType<typeof papelControllerListarPermissoes>>>
export type PapelControllerListarPermissoesQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function usePapelControllerListarPermissoes<TData = Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof papelControllerListarPermissoes>>,
          TError,
          Awaited<ReturnType<typeof papelControllerListarPermissoes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePapelControllerListarPermissoes<TData = Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof papelControllerListarPermissoes>>,
          TError,
          Awaited<ReturnType<typeof papelControllerListarPermissoes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePapelControllerListarPermissoes<TData = Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePapelControllerListarPermissoes<TData = Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof papelControllerListarPermissoes>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPapelControllerListarPermissoesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type papelControllerVincularResponse201 = {
  data: void
  status: 201
}

export type papelControllerVincularResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type papelControllerVincularResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type papelControllerVincularResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type papelControllerVincularResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type papelControllerVincularResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type papelControllerVincularResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type papelControllerVincularResponseSuccess = (papelControllerVincularResponse201) & {
  headers: Headers;
};
export type papelControllerVincularResponseError = (papelControllerVincularResponse400 | papelControllerVincularResponse401 | papelControllerVincularResponse403 | papelControllerVincularResponse404 | papelControllerVincularResponse409 | papelControllerVincularResponse429) & {
  headers: Headers;
};

export type papelControllerVincularResponse = (papelControllerVincularResponseSuccess | papelControllerVincularResponseError)

export const getPapelControllerVincularUrl = (id: number,) => {




  return `${apiBaseUrl}/papeis/${id}/permissoes`
}

export const papelControllerVincular = async (id: number,
    vincularPermissaoDto: VincularPermissaoDto, options?: Parameters<typeof httpClient>[1]): Promise<papelControllerVincularResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<papelControllerVincularResponse>(getPapelControllerVincularUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(vincularPermissaoDto)
  }
);}





export const getPapelControllerVincularMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerVincular>>, TError,PapelControllerVincularMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof papelControllerVincular>>, TError,PapelControllerVincularMutationVariables, TContext> => {

const mutationKey = ['papelControllerVincular'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof papelControllerVincular>>, PapelControllerVincularMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  papelControllerVincular(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PapelControllerVincularMutationResult = NonNullable<Awaited<ReturnType<typeof papelControllerVincular>>>
    export type PapelControllerVincularMutationBody = VincularPermissaoDto
    export type PapelControllerVincularMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type PapelControllerVincularMutationVariables = {id: number;data: VincularPermissaoDto}

    export const usePapelControllerVincular = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerVincular>>, TError,PapelControllerVincularMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof papelControllerVincular>>,
        TError,
        PapelControllerVincularMutationVariables,
        TContext
      > => {
      return useMutation(getPapelControllerVincularMutationOptions(options), queryClient);
    }
    export type papelControllerAtualizarVinculoResponse200 = {
  data: void
  status: 200
}

export type papelControllerAtualizarVinculoResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type papelControllerAtualizarVinculoResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type papelControllerAtualizarVinculoResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type papelControllerAtualizarVinculoResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type papelControllerAtualizarVinculoResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type papelControllerAtualizarVinculoResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type papelControllerAtualizarVinculoResponseSuccess = (papelControllerAtualizarVinculoResponse200) & {
  headers: Headers;
};
export type papelControllerAtualizarVinculoResponseError = (papelControllerAtualizarVinculoResponse400 | papelControllerAtualizarVinculoResponse401 | papelControllerAtualizarVinculoResponse403 | papelControllerAtualizarVinculoResponse404 | papelControllerAtualizarVinculoResponse409 | papelControllerAtualizarVinculoResponse429) & {
  headers: Headers;
};

export type papelControllerAtualizarVinculoResponse = (papelControllerAtualizarVinculoResponseSuccess | papelControllerAtualizarVinculoResponseError)

export const getPapelControllerAtualizarVinculoUrl = (id: number,
    idPermissao: number,) => {




  return `${apiBaseUrl}/papeis/${id}/permissoes/${idPermissao}`
}

export const papelControllerAtualizarVinculo = async (id: number,
    idPermissao: number,
    atualizarPapelPermissaoDto: AtualizarPapelPermissaoDto, options?: Parameters<typeof httpClient>[1]): Promise<papelControllerAtualizarVinculoResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<papelControllerAtualizarVinculoResponse>(getPapelControllerAtualizarVinculoUrl(id,idPermissao),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarPapelPermissaoDto)
  }
);}





export const getPapelControllerAtualizarVinculoMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerAtualizarVinculo>>, TError,PapelControllerAtualizarVinculoMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof papelControllerAtualizarVinculo>>, TError,PapelControllerAtualizarVinculoMutationVariables, TContext> => {

const mutationKey = ['papelControllerAtualizarVinculo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof papelControllerAtualizarVinculo>>, PapelControllerAtualizarVinculoMutationVariables> = (props) => {
          const {id,idPermissao,data} = props ?? {};

          return  papelControllerAtualizarVinculo(id,idPermissao,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PapelControllerAtualizarVinculoMutationResult = NonNullable<Awaited<ReturnType<typeof papelControllerAtualizarVinculo>>>
    export type PapelControllerAtualizarVinculoMutationBody = AtualizarPapelPermissaoDto
    export type PapelControllerAtualizarVinculoMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type PapelControllerAtualizarVinculoMutationVariables = {id: number;idPermissao: number;data: AtualizarPapelPermissaoDto}

    export const usePapelControllerAtualizarVinculo = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerAtualizarVinculo>>, TError,PapelControllerAtualizarVinculoMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof papelControllerAtualizarVinculo>>,
        TError,
        PapelControllerAtualizarVinculoMutationVariables,
        TContext
      > => {
      return useMutation(getPapelControllerAtualizarVinculoMutationOptions(options), queryClient);
    }
    export type papelControllerDesvincularResponse200 = {
  data: void
  status: 200
}

export type papelControllerDesvincularResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type papelControllerDesvincularResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type papelControllerDesvincularResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type papelControllerDesvincularResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type papelControllerDesvincularResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type papelControllerDesvincularResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type papelControllerDesvincularResponseSuccess = (papelControllerDesvincularResponse200) & {
  headers: Headers;
};
export type papelControllerDesvincularResponseError = (papelControllerDesvincularResponse400 | papelControllerDesvincularResponse401 | papelControllerDesvincularResponse403 | papelControllerDesvincularResponse404 | papelControllerDesvincularResponse409 | papelControllerDesvincularResponse429) & {
  headers: Headers;
};

export type papelControllerDesvincularResponse = (papelControllerDesvincularResponseSuccess | papelControllerDesvincularResponseError)

export const getPapelControllerDesvincularUrl = (id: number,
    idPermissao: number,) => {




  return `${apiBaseUrl}/papeis/${id}/permissoes/${idPermissao}`
}

export const papelControllerDesvincular = async (id: number,
    idPermissao: number, options?: Parameters<typeof httpClient>[1]): Promise<papelControllerDesvincularResponse> => {

  return httpClient<papelControllerDesvincularResponse>(getPapelControllerDesvincularUrl(id,idPermissao),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getPapelControllerDesvincularMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerDesvincular>>, TError,PapelControllerDesvincularMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof papelControllerDesvincular>>, TError,PapelControllerDesvincularMutationVariables, TContext> => {

const mutationKey = ['papelControllerDesvincular'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof papelControllerDesvincular>>, PapelControllerDesvincularMutationVariables> = (props) => {
          const {id,idPermissao} = props ?? {};

          return  papelControllerDesvincular(id,idPermissao,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PapelControllerDesvincularMutationResult = NonNullable<Awaited<ReturnType<typeof papelControllerDesvincular>>>

    export type PapelControllerDesvincularMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type PapelControllerDesvincularMutationVariables = {id: number;idPermissao: number}

    export const usePapelControllerDesvincular = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof papelControllerDesvincular>>, TError,PapelControllerDesvincularMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof papelControllerDesvincular>>,
        TError,
        PapelControllerDesvincularMutationVariables,
        TContext
      > => {
      return useMutation(getPapelControllerDesvincularMutationOptions(options), queryClient);
    }
