/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AtualizarFilialDto,
  CriarFilialDto,
  FilialControllerAtualizar200,
  FilialControllerBuscar200,
  FilialControllerCriar201,
  FilialControllerListarParams
} from '../models';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type filialControllerCriarResponse201 = {
  data: FilialControllerCriar201
  status: 201
}

export type filialControllerCriarResponseSuccess = (filialControllerCriarResponse201) & {
  headers: Headers;
};
;

export type filialControllerCriarResponse = (filialControllerCriarResponseSuccess)

export const getFilialControllerCriarUrl = () => {




  return `/filiais`
}

export const filialControllerCriar = async (criarFilialDto: CriarFilialDto, options?: RequestInit): Promise<filialControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getFilialControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarFilialDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filialControllerCriarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as filialControllerCriarResponse
}





export const getFilialControllerCriarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filialControllerCriar>>, TError,FilialControllerCriarMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filialControllerCriar>>, TError,FilialControllerCriarMutationVariables, TContext> => {

const mutationKey = ['filialControllerCriar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filialControllerCriar>>, FilialControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  filialControllerCriar(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilialControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof filialControllerCriar>>>
    export type FilialControllerCriarMutationBody = CriarFilialDto
    export type FilialControllerCriarMutationError = unknown
    export type FilialControllerCriarMutationVariables = {data: CriarFilialDto}

    export const useFilialControllerCriar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filialControllerCriar>>, TError,FilialControllerCriarMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filialControllerCriar>>,
        TError,
        FilialControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getFilialControllerCriarMutationOptions(options), queryClient);
    }
    export type filialControllerListarResponse200 = {
  data: void
  status: 200
}

export type filialControllerListarResponseSuccess = (filialControllerListarResponse200) & {
  headers: Headers;
};
;

export type filialControllerListarResponse = (filialControllerListarResponseSuccess)

export const getFilialControllerListarUrl = (params: FilialControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/filiais?${stringifiedParams}` : `/filiais`
}

export const filialControllerListar = async (params: FilialControllerListarParams, options?: RequestInit): Promise<filialControllerListarResponse> => {

  const res = await fetch(getFilialControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filialControllerListarResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filialControllerListarResponse
}





export const getFilialControllerListarQueryKey = (params?: FilialControllerListarParams,) => {
    return [
    `/filiais`, ...(params ? [params] : [])
    ] as const;
    }


export const getFilialControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof filialControllerListar>>, TError = unknown>(params: FilialControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerListar>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilialControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filialControllerListar>>> = ({ signal }) => filialControllerListar(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filialControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilialControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof filialControllerListar>>>
export type FilialControllerListarQueryError = unknown


export function useFilialControllerListar<TData = Awaited<ReturnType<typeof filialControllerListar>>, TError = unknown>(
 params: FilialControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filialControllerListar>>,
          TError,
          Awaited<ReturnType<typeof filialControllerListar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilialControllerListar<TData = Awaited<ReturnType<typeof filialControllerListar>>, TError = unknown>(
 params: FilialControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filialControllerListar>>,
          TError,
          Awaited<ReturnType<typeof filialControllerListar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilialControllerListar<TData = Awaited<ReturnType<typeof filialControllerListar>>, TError = unknown>(
 params: FilialControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerListar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilialControllerListar<TData = Awaited<ReturnType<typeof filialControllerListar>>, TError = unknown>(
 params: FilialControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerListar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilialControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type filialControllerBuscarResponse200 = {
  data: FilialControllerBuscar200
  status: 200
}

export type filialControllerBuscarResponseSuccess = (filialControllerBuscarResponse200) & {
  headers: Headers;
};
;

export type filialControllerBuscarResponse = (filialControllerBuscarResponseSuccess)

export const getFilialControllerBuscarUrl = (id: number,) => {




  return `/filiais/${id}`
}

export const filialControllerBuscar = async (id: number, options?: RequestInit): Promise<filialControllerBuscarResponse> => {

  const res = await fetch(getFilialControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filialControllerBuscarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as filialControllerBuscarResponse
}





export const getFilialControllerBuscarQueryKey = (id: number,) => {
    return [
    `/filiais/${id}`
    ] as const;
    }


export const getFilialControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof filialControllerBuscar>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilialControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filialControllerBuscar>>> = ({ signal }) => filialControllerBuscar(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filialControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilialControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof filialControllerBuscar>>>
export type FilialControllerBuscarQueryError = unknown


export function useFilialControllerBuscar<TData = Awaited<ReturnType<typeof filialControllerBuscar>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filialControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof filialControllerBuscar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilialControllerBuscar<TData = Awaited<ReturnType<typeof filialControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filialControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof filialControllerBuscar>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilialControllerBuscar<TData = Awaited<ReturnType<typeof filialControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilialControllerBuscar<TData = Awaited<ReturnType<typeof filialControllerBuscar>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filialControllerBuscar>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilialControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type filialControllerAtualizarResponse200 = {
  data: FilialControllerAtualizar200
  status: 200
}

export type filialControllerAtualizarResponseSuccess = (filialControllerAtualizarResponse200) & {
  headers: Headers;
};
;

export type filialControllerAtualizarResponse = (filialControllerAtualizarResponseSuccess)

export const getFilialControllerAtualizarUrl = (id: number,) => {




  return `/filiais/${id}`
}

export const filialControllerAtualizar = async (id: number,
    atualizarFilialDto: AtualizarFilialDto, options?: RequestInit): Promise<filialControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
const res = await fetch(getFilialControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarFilialDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filialControllerAtualizarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as filialControllerAtualizarResponse
}





export const getFilialControllerAtualizarMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filialControllerAtualizar>>, TError,FilialControllerAtualizarMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filialControllerAtualizar>>, TError,FilialControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['filialControllerAtualizar'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filialControllerAtualizar>>, FilialControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  filialControllerAtualizar(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilialControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof filialControllerAtualizar>>>
    export type FilialControllerAtualizarMutationBody = AtualizarFilialDto
    export type FilialControllerAtualizarMutationError = unknown
    export type FilialControllerAtualizarMutationVariables = {id: number;data: AtualizarFilialDto}

    export const useFilialControllerAtualizar = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filialControllerAtualizar>>, TError,FilialControllerAtualizarMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filialControllerAtualizar>>,
        TError,
        FilialControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getFilialControllerAtualizarMutationOptions(options), queryClient);
    }
    export type filialControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type filialControllerRemoverResponseSuccess = (filialControllerRemoverResponse200) & {
  headers: Headers;
};
;

export type filialControllerRemoverResponse = (filialControllerRemoverResponseSuccess)

export const getFilialControllerRemoverUrl = (id: number,) => {




  return `/filiais/${id}`
}

export const filialControllerRemover = async (id: number, options?: RequestInit): Promise<filialControllerRemoverResponse> => {

  const res = await fetch(getFilialControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filialControllerRemoverResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filialControllerRemoverResponse
}





export const getFilialControllerRemoverMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filialControllerRemover>>, TError,FilialControllerRemoverMutationVariables, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filialControllerRemover>>, TError,FilialControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['filialControllerRemover'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filialControllerRemover>>, FilialControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  filialControllerRemover(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilialControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof filialControllerRemover>>>

    export type FilialControllerRemoverMutationError = unknown
    export type FilialControllerRemoverMutationVariables = {id: number}

    export const useFilialControllerRemover = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filialControllerRemover>>, TError,FilialControllerRemoverMutationVariables, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filialControllerRemover>>,
        TError,
        FilialControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getFilialControllerRemoverMutationOptions(options), queryClient);
    }
