/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API Agendador de Barbearia
 * Contrato OpenAPI da API REST do Agendador de Barbearia.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  apiBaseUrl
} from '../client';

import type {
  AtualizarClienteDto,
  ClienteControllerListarParams,
  CriarClienteDto,
  ErroRespostaDto,
  LimiteRequisicoesRespostaDto
} from '../models';

import { httpClient } from '.././http-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type clienteControllerCriarResponse201 = {
  data: void
  status: 201
}

export type clienteControllerCriarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type clienteControllerCriarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type clienteControllerCriarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type clienteControllerCriarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type clienteControllerCriarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type clienteControllerCriarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type clienteControllerCriarResponseSuccess = (clienteControllerCriarResponse201) & {
  headers: Headers;
};
export type clienteControllerCriarResponseError = (clienteControllerCriarResponse400 | clienteControllerCriarResponse401 | clienteControllerCriarResponse403 | clienteControllerCriarResponse404 | clienteControllerCriarResponse409 | clienteControllerCriarResponse429) & {
  headers: Headers;
};

export type clienteControllerCriarResponse = (clienteControllerCriarResponseSuccess | clienteControllerCriarResponseError)

export const getClienteControllerCriarUrl = () => {




  return `${apiBaseUrl}/clientes`
}

export const clienteControllerCriar = async (criarClienteDto: CriarClienteDto, options?: Parameters<typeof httpClient>[1]): Promise<clienteControllerCriarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<clienteControllerCriarResponse>(getClienteControllerCriarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(criarClienteDto)
  }
);}





export const getClienteControllerCriarMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clienteControllerCriar>>, TError,ClienteControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof clienteControllerCriar>>, TError,ClienteControllerCriarMutationVariables, TContext> => {

const mutationKey = ['clienteControllerCriar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clienteControllerCriar>>, ClienteControllerCriarMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  clienteControllerCriar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClienteControllerCriarMutationResult = NonNullable<Awaited<ReturnType<typeof clienteControllerCriar>>>
    export type ClienteControllerCriarMutationBody = CriarClienteDto
    export type ClienteControllerCriarMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type ClienteControllerCriarMutationVariables = {data: CriarClienteDto}

    export const useClienteControllerCriar = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clienteControllerCriar>>, TError,ClienteControllerCriarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clienteControllerCriar>>,
        TError,
        ClienteControllerCriarMutationVariables,
        TContext
      > => {
      return useMutation(getClienteControllerCriarMutationOptions(options), queryClient);
    }
    export type clienteControllerListarResponse200 = {
  data: void
  status: 200
}

export type clienteControllerListarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type clienteControllerListarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type clienteControllerListarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type clienteControllerListarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type clienteControllerListarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type clienteControllerListarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type clienteControllerListarResponseSuccess = (clienteControllerListarResponse200) & {
  headers: Headers;
};
export type clienteControllerListarResponseError = (clienteControllerListarResponse400 | clienteControllerListarResponse401 | clienteControllerListarResponse403 | clienteControllerListarResponse404 | clienteControllerListarResponse409 | clienteControllerListarResponse429) & {
  headers: Headers;
};

export type clienteControllerListarResponse = (clienteControllerListarResponseSuccess | clienteControllerListarResponseError)

export const getClienteControllerListarUrl = (params?: ClienteControllerListarParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${apiBaseUrl}/clientes?${stringifiedParams}` : `${apiBaseUrl}/clientes`
}

export const clienteControllerListar = async (params?: ClienteControllerListarParams, options?: Parameters<typeof httpClient>[1]): Promise<clienteControllerListarResponse> => {

  return httpClient<clienteControllerListarResponse>(getClienteControllerListarUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getClienteControllerListarQueryKey = (params?: ClienteControllerListarParams,) => {
    return [
    `${apiBaseUrl}/clientes`, ...(params ? [params] : [])
    ] as const;
    }


export const getClienteControllerListarQueryOptions = <TData = Awaited<ReturnType<typeof clienteControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(params?: ClienteControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClienteControllerListarQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof clienteControllerListar>>> = ({ signal }) => clienteControllerListar(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clienteControllerListar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClienteControllerListarQueryResult = NonNullable<Awaited<ReturnType<typeof clienteControllerListar>>>
export type ClienteControllerListarQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useClienteControllerListar<TData = Awaited<ReturnType<typeof clienteControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params: undefined |  ClienteControllerListarParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerListar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clienteControllerListar>>,
          TError,
          Awaited<ReturnType<typeof clienteControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClienteControllerListar<TData = Awaited<ReturnType<typeof clienteControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: ClienteControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerListar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clienteControllerListar>>,
          TError,
          Awaited<ReturnType<typeof clienteControllerListar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClienteControllerListar<TData = Awaited<ReturnType<typeof clienteControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: ClienteControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useClienteControllerListar<TData = Awaited<ReturnType<typeof clienteControllerListar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 params?: ClienteControllerListarParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerListar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClienteControllerListarQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type clienteControllerBuscarResponse200 = {
  data: void
  status: 200
}

export type clienteControllerBuscarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type clienteControllerBuscarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type clienteControllerBuscarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type clienteControllerBuscarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type clienteControllerBuscarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type clienteControllerBuscarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type clienteControllerBuscarResponseSuccess = (clienteControllerBuscarResponse200) & {
  headers: Headers;
};
export type clienteControllerBuscarResponseError = (clienteControllerBuscarResponse400 | clienteControllerBuscarResponse401 | clienteControllerBuscarResponse403 | clienteControllerBuscarResponse404 | clienteControllerBuscarResponse409 | clienteControllerBuscarResponse429) & {
  headers: Headers;
};

export type clienteControllerBuscarResponse = (clienteControllerBuscarResponseSuccess | clienteControllerBuscarResponseError)

export const getClienteControllerBuscarUrl = (id: number,) => {




  return `${apiBaseUrl}/clientes/${id}`
}

export const clienteControllerBuscar = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<clienteControllerBuscarResponse> => {

  return httpClient<clienteControllerBuscarResponse>(getClienteControllerBuscarUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getClienteControllerBuscarQueryKey = (id: number,) => {
    return [
    `${apiBaseUrl}/clientes/${id}`
    ] as const;
    }


export const getClienteControllerBuscarQueryOptions = <TData = Awaited<ReturnType<typeof clienteControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClienteControllerBuscarQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof clienteControllerBuscar>>> = ({ signal }) => clienteControllerBuscar(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clienteControllerBuscar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClienteControllerBuscarQueryResult = NonNullable<Awaited<ReturnType<typeof clienteControllerBuscar>>>
export type ClienteControllerBuscarQueryError = ErroRespostaDto | LimiteRequisicoesRespostaDto


export function useClienteControllerBuscar<TData = Awaited<ReturnType<typeof clienteControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerBuscar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clienteControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof clienteControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClienteControllerBuscar<TData = Awaited<ReturnType<typeof clienteControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerBuscar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clienteControllerBuscar>>,
          TError,
          Awaited<ReturnType<typeof clienteControllerBuscar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClienteControllerBuscar<TData = Awaited<ReturnType<typeof clienteControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useClienteControllerBuscar<TData = Awaited<ReturnType<typeof clienteControllerBuscar>>, TError = ErroRespostaDto | LimiteRequisicoesRespostaDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clienteControllerBuscar>>, TError, TData>>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClienteControllerBuscarQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type clienteControllerAtualizarResponse200 = {
  data: void
  status: 200
}

export type clienteControllerAtualizarResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type clienteControllerAtualizarResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type clienteControllerAtualizarResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type clienteControllerAtualizarResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type clienteControllerAtualizarResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type clienteControllerAtualizarResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type clienteControllerAtualizarResponseSuccess = (clienteControllerAtualizarResponse200) & {
  headers: Headers;
};
export type clienteControllerAtualizarResponseError = (clienteControllerAtualizarResponse400 | clienteControllerAtualizarResponse401 | clienteControllerAtualizarResponse403 | clienteControllerAtualizarResponse404 | clienteControllerAtualizarResponse409 | clienteControllerAtualizarResponse429) & {
  headers: Headers;
};

export type clienteControllerAtualizarResponse = (clienteControllerAtualizarResponseSuccess | clienteControllerAtualizarResponseError)

export const getClienteControllerAtualizarUrl = (id: number,) => {




  return `${apiBaseUrl}/clientes/${id}`
}

export const clienteControllerAtualizar = async (id: number,
    atualizarClienteDto: AtualizarClienteDto, options?: Parameters<typeof httpClient>[1]): Promise<clienteControllerAtualizarResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return httpClient<clienteControllerAtualizarResponse>(getClienteControllerAtualizarUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizarClienteDto)
  }
);}





export const getClienteControllerAtualizarMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clienteControllerAtualizar>>, TError,ClienteControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof clienteControllerAtualizar>>, TError,ClienteControllerAtualizarMutationVariables, TContext> => {

const mutationKey = ['clienteControllerAtualizar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clienteControllerAtualizar>>, ClienteControllerAtualizarMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  clienteControllerAtualizar(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClienteControllerAtualizarMutationResult = NonNullable<Awaited<ReturnType<typeof clienteControllerAtualizar>>>
    export type ClienteControllerAtualizarMutationBody = AtualizarClienteDto
    export type ClienteControllerAtualizarMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type ClienteControllerAtualizarMutationVariables = {id: number;data: AtualizarClienteDto}

    export const useClienteControllerAtualizar = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clienteControllerAtualizar>>, TError,ClienteControllerAtualizarMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clienteControllerAtualizar>>,
        TError,
        ClienteControllerAtualizarMutationVariables,
        TContext
      > => {
      return useMutation(getClienteControllerAtualizarMutationOptions(options), queryClient);
    }
    export type clienteControllerRemoverResponse200 = {
  data: void
  status: 200
}

export type clienteControllerRemoverResponse400 = {
  data: ErroRespostaDto
  status: 400
}

export type clienteControllerRemoverResponse401 = {
  data: ErroRespostaDto
  status: 401
}

export type clienteControllerRemoverResponse403 = {
  data: ErroRespostaDto
  status: 403
}

export type clienteControllerRemoverResponse404 = {
  data: ErroRespostaDto
  status: 404
}

export type clienteControllerRemoverResponse409 = {
  data: ErroRespostaDto
  status: 409
}

export type clienteControllerRemoverResponse429 = {
  data: LimiteRequisicoesRespostaDto
  status: 429
}

export type clienteControllerRemoverResponseSuccess = (clienteControllerRemoverResponse200) & {
  headers: Headers;
};
export type clienteControllerRemoverResponseError = (clienteControllerRemoverResponse400 | clienteControllerRemoverResponse401 | clienteControllerRemoverResponse403 | clienteControllerRemoverResponse404 | clienteControllerRemoverResponse409 | clienteControllerRemoverResponse429) & {
  headers: Headers;
};

export type clienteControllerRemoverResponse = (clienteControllerRemoverResponseSuccess | clienteControllerRemoverResponseError)

export const getClienteControllerRemoverUrl = (id: number,) => {




  return `${apiBaseUrl}/clientes/${id}`
}

export const clienteControllerRemover = async (id: number, options?: Parameters<typeof httpClient>[1]): Promise<clienteControllerRemoverResponse> => {

  return httpClient<clienteControllerRemoverResponse>(getClienteControllerRemoverUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getClienteControllerRemoverMutationOptions = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clienteControllerRemover>>, TError,ClienteControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
): UseMutationOptions<Awaited<ReturnType<typeof clienteControllerRemover>>, TError,ClienteControllerRemoverMutationVariables, TContext> => {

const mutationKey = ['clienteControllerRemover'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clienteControllerRemover>>, ClienteControllerRemoverMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  clienteControllerRemover(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClienteControllerRemoverMutationResult = NonNullable<Awaited<ReturnType<typeof clienteControllerRemover>>>

    export type ClienteControllerRemoverMutationError = ErroRespostaDto | LimiteRequisicoesRespostaDto
    export type ClienteControllerRemoverMutationVariables = {id: number}

    export const useClienteControllerRemover = <TError = ErroRespostaDto | LimiteRequisicoesRespostaDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clienteControllerRemover>>, TError,ClienteControllerRemoverMutationVariables, TContext>, request?: SecondParameter<typeof httpClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clienteControllerRemover>>,
        TError,
        ClienteControllerRemoverMutationVariables,
        TContext
      > => {
      return useMutation(getClienteControllerRemoverMutationOptions(options), queryClient);
    }
